package params

import (
	smodel "gitlab.mobvista.com/ADN/structs/model"
)

type BiddingRequest struct {
	AdType                    int              `json:"adType,omitempty"`
	ImpID                     string           `json:"impId,omitempty"`
	BidId                     string           `json:"bidId,omitempty"`
	HttpReq                   int              `json:"httpReq,omitempty"`
	AppFrequencyCap           int              `json:"appFrequencyCap,omitempty"`
	Language                  string           `json:"language,omitempty"`
	JumpTypeConfig            map[string]int32 `json:"jumpTypeConfig,omitempty"`
	AppDevinfoEncrypt         int              `json:"devinfoEncrypt,omitempty"`
	UnitEndCard               *smodel.EndCard  `json:"unitEndCard,omitempty"`
	AppId                     int64            `json:"appId,omitempty"`
	UnitId                    int64            `json:"unitId,omitempty"`
	Platform                  int              `json:"platform,omitempty"`
	OsVersion                 string           `json:"osVersion,omitempty"`
	ClientIp                  string           `json:"clientIp,omitempty"`
	AppVersionName            string           `json:"appVersionName,omitempty"`
	AppVersionCode            string           `json:"appVersionCode,omitempty"`
	Orientation               int              `json:"orientation,omitempty"`
	Brand                     string           `json:"brand,omitempty"`
	Model                     string           `json:"model,omitempty"`
	Oaid                      string           `json:"Oaid,omitempty"`
	OaidMd5                   string           `json:"OaidMd5,omitempty"`
	AndroidId                 string           `json:"androidId,omitempty"`
	AndroidIdMd5              string           `json:"androidIdMd5,omitempty"`
	Imei                      string           `json:"Imei,omitempty"`
	ImeiMd5                   string           `json:"ImeiMd5,omitempty"`
	Gaid                      string           `json:"Gaid,omitempty"`
	GaidMd5                   string           `json:"GaidMd5,omitempty"`
	Idfa                      string           `json:"Idfa,omitempty"`
	IdfaMd5                   string           `json:"IdfaMd5,omitempty"`
	MNC                       string           `json:"mnc,omitempty"`
	MCC                       string           `json:"mcc,omitempty"`
	NetworkType               int              `json:"networkType,omitempty"`
	UserAgent                 string           `json:"useragent,omitempty"`
	SdkVersion                string           `json:"sdkversion,omitempty"`
	ScreenSize                string           `json:"screenSize,omitempty"`
	Channel                   int              `json:"channel,omitempty"`
	NVTemplate                int32            `json:"nvTemplate,omitemty"`
	VideoEndType              int              `json:"videoEndType,omitempty"`
	AppStorekitLoading        int32            `json:"appStorekitLoading,omitempty"`
	Scenario                  string           `json:"scenario,omitempty"`
	Algorithm                 string           `json:"algorithm,omitempty"`
	CountryCode               string           `json:"countryCode,omitempty"`
	CityCode                  string           `json:"cityCode,omitempty"`
	CityName                  string           `json:"cityName,omitempty"`
	ReplaceBrand              string           `json:"replaceBrand,omitempty"`
	ReplaceModel              string           `json:"replaceModel,omitempty"`
	AppName                   string           `json:"appName,omitempty"`
	RealPackageName           string           `json:"realPackageName,omitempty"`
	RequestType               int              `json:"requestType,omitempty"`
	PublisherId               int64            `json:"publisherId,omitempty"`
	PublisherType             int              `json:"publisherType,omitempty"`
	FormatOrientation         int              `json:"formatOrientation,omitempty"`
	IfSupportSeperateCreative int32            `json:"ifSupportSeperateCreative,omitempty"`
	Offset                    int32            `json:"offset,omitempty"`
	SysId                     string           `json:"sysId,omitempty"`
	BkupId                    string           `json:"bkupId,omitempty"`
	ExtSysId                  string           `json:"extSysId,omitempty"`
	Price                     float64          `json:"price,omitempty"`
	ExtflowTagId              int              `json:"extFlowTagId,omitempty"`
	RandValue                 int              `json:"randValue,omitempty"`
	AdNum                     int              `json:"adNum,omitempty"`
	ReqKeyName                string           `json:"reqKeyName,omitempty"`
	PackageName               string           `json:"packageName,omitempty"`
	ExtsystemUseragent        string           `json:"extsystemUseragent,omitempty"`
	PriceFactor               string           `json:"priceFactor,omitempty"`
	UnitNVTemplate            int32            `json:"unitNVTemplate,omitempty"`
	ScreenWidth               int32            `json:"screenWidth,omitempty"`
	ScreenHeight              int32            `json:"screenHeight,omitempty"`
	UnitBtClass               int              `json:"unitBtClass,omitempty"`
	AppBtClass                int              `json:"appBtClass,omitempty"`
	ImpExcludePkg             string           `json:"impExcludePkg,omitempty"`
	UnitAlac                  int              `json:"unitAlac,omitempty"`
	UnitAlecfc                int              `json:"unitAlecfc,omitempty"`
	UnitMof                   int              `json:"unitMof,omitempty"`
	MofUnitId                 int64            `json:"mofUnitId,omitempty"`
	BigTemplate               bool             `json:"bigTemplate,omitempty"`
	RandNum                   int32            `json:"randNum,omitempty"`
	ApiVersion                string           `json:"apiVersion,omitempty"`
	RemovePubImp              bool             `json:"removePubImp,omitempty"`
	PlacementId               int64            `json:"placementId,omitempty"`
	BidTestMode               int32            `json:"bidTestMode,omitempty"`
	BidFloor                  float64          `json:"bidFloor,omitempty"`
	MediationName             string           `json:"mediationName,omitempty"`
	Extra3                    string           `json:"extra3,omitempty"`
	ExtAlgo                   string           `json:"extAlgo,omitempty"`
	ExtAdxAlgo                string           `json:"extAdxAlgo,omitempty"`
	Add2ExtData2              ExtData          `json:"add2ExtData2,omitempty"`
	BundleId                  string           `json:"bundleId,omitempty"`
	DcoTestFlag               int32            `json:"dcoTestFlag,omitempty"`
	DspID                     string           `json:"dspId,omitempty"`
}
