package params

import (
	"gitlab.mobvista.com/ADN/mtg_openrtb/pkg/mtgrtb"
	smodel "gitlab.mobvista.com/ADN/structs/model"
)

type LoadReqData struct {
	BidId                     string
	HBidId                    string
	PublisherId               int64
	PublisherIdStr            string
	PublisherType             int
	AppIdStr                  string
	AppId                     int64
	UnitId                    int64
	UnitIdStr                 string
	Token                     string
	Path                      string
	UserAgent                 string
	ClientIp                  string
	CountryCode               string
	CityCode                  string
	CityName                  string
	Platform                  int
	Os                        string
	OsVersion                 string
	SdkVersion                string
	AppVersionName            string
	Brand                     string
	Model                     string
	ScreenSize                string
	Orientation               int
	Language                  string
	NetworkType               int
	Mnc                       string
	Mcc                       string
	Imei                      string
	ImeiMd5                   string
	Oaid                      string
	OaidMd5                   string
	AndroidId                 string
	AndroidIdMd5              string
	Gaid                      string
	GaidMd5                   string
	Idfa                      string
	IdfaMd5                   string
	PlayInfo                  string
	ImpId                     string
	Bid                       *mtgrtb.BidResponse_SeatBid_Bid
	BidResp                   *mtgrtb.BidResponse
	FilterCode                int
	IsAsResp                  bool
	DspId                     int64
	AdType                    int
	Ad                        *Ad
	Ads                       []*Ad
	DspExt                    string
	FakePrice                 string
	PriceFactor               string
	Cate                      int
	HttpReq                   int
	AppFrequencyCap           int
	JumpTypeConfig            map[string]int32
	JumpType                  string
	ExtdeleteDevid            int
	Extra10                   string
	AppDevinfoEncrypt         int
	Mac                       string
	PackageName               string
	CreativeAdType            int
	AdvCreativeID             int
	CreativeName              string
	Extra5                    string
	Domain                    string
	AdvertiserId              int64
	Extra                     string
	Extra8                    int
	Extra13                   int32
	Extra14                   int64
	Extra16                   int
	Extra7                    int
	Extbtclass                int
	Extfinalsubid             int64
	ExtinstallFrom            int
	ExtnativeVideo            int
	ExtflowTagId              int
	Extendcard                int64
	ExtdspRealAppid           int64
	ExtfinalPackageName       string
	ExtMtgId                  int64
	Extnativex                int
	CreativeId                int64
	ImageCreativeId           int64
	VideoCreativeId           int64
	Extattr                   int
	Extctype                  int32
	Extrvtemplate             int
	Extplayable               int
	Extb2t                    int
	Extchannel                string
	Extabtest2                int
	Extbp                     string
	Extsource                 int32
	ExtappearUa               int
	ExtCDNAbTest              int
	ExtMpNormalMap            string
	Extplayable2              int
	Extabtest3                string
	ExtData2Obj               map[string]interface{}
	ExtData2                  string
	BidPrice                  float64
	ParamQ                    string
	ImageSize                 string
	NetworkTypeName           string
	Extra3                    string
	Extra4                    string
	RemoteIP                  string
	SessionID                 string
	ParentSessionID           string
	Idfv                      string
	OpenIdfa                  string
	Extstats                  string
	Extstats2                 string
	ReplaceBrand              string
	ReplaceModel              string
	ExtCreativeNew            string
	ExtSysId                  string
	ApiVersion                float64
	ParamAL                   string
	ParamR                    string
	UnitEndCard               *smodel.EndCard
	CampaignId                int64
	Algorithm                 string
	Scenario                  string
	AdTypeStr                 string
	Channel                   int
	Nbr                       int
	Price                     float64
	NVTemplate                int32
	VideoEndType              int
	AppStorekitLoading        int32
	ExtApiVersion             string
	AppName                   string
	RealPackageName           string
	RequestType               int
	FormatOrientation         int
	IfSupportSeperateCreative int32
	Extalgo                   string
	Extra9                    string
	ServerIp                  string
	RemoteIp                  string
	Extra15                   string
	Extra20                   string
	ExtpackageName            string
	ExtrushNoPre              int
	ExtthirdCid               string
	ExtifLowerImp             string
	ExtsystemUseragent        string
	RandValue                 int
	AdBackend                 string
	AdBackendData             string
	BackendConfig             string
	AdNum                     int
	ReqKeyName                string
	OfferType                 int32
	ClickUa                   int
	MidwayCreative            []int
	MidwayCreativeData        string
	IsCleanRV                 bool
	EndCardUrl                string
	EndScreenTemplateId       int32
	UnitNVTemplate            int32
	Extnvt2                   int32
	EndCardTemplateId         int64
	ScreenWidth               int32
	ScreenHeight              int32
	RejectCode                int
	Host                      string
	BannerUrl                 string
	BannerHtml                string
	SplashAdUrl               string
	SplashAdHtml              string
	UnitBtClass               int
	AppBtClass                int
	ImpExcludePkg             string
	UnitAlac                  int
	UnitAlecfc                int
	UnitMof                   int
	MofUnitId                 int64
	MofAbFlag                 bool
	NewMoreOfferFlag          bool
	NewMofImpFlag             bool
	CloseAdTag                string
	NewMoreOfferParams        string
	ImgFMD5                   string
	CtnSizeTag                string
	RemovePubImp              bool
	BigTemplateFlag           bool
	RandNum                   int32
	BigTemplateId             int64
	BigTemplateSlotMap        map[int32]int64
	ExtBigTplOfferData        string
	ExtBigTplOfferDataList    []string
	ExtSlotId                 string
	ExtBigTemId               string
	BigTempalteAdxPvUrl       []string
	BigTemplateUrl            string
	PriceIn                   float64
	PriceOut                  float64
	LocalPriceIn              float64
	PlacementId               int64
	Dmt                       float64
	Dmf                       float64
	Ct                        string
	PowerRate                 int
	Charging                  int
	TotalMemory               string
	ResidualMemory            string
	BidTestMode               int32
	BidFloor                  float64
	MediationName             string
	ToponChannelInfo          string
	ExtAlgo                   string
	ExtAdxAlgo                string
	ExtData2Log               string
	Add2ExtData2              ExtData
	BundleId                  string
	DcoTestTag                int32
	VideoTplV11Tag            bool // 判断视频模版是否为v11模版，是则需要读取fake的大模版url返回给sdk
}
