package constant

const (
	CREATIVE_AD_TYPE_BANNER = iota + 1
	CREATIVE_AD_TYPE_INTERSTITIAL
	CREATIVE_AD_TYPE_NATIVE
	CREATIVE_AD_TYPE_APPWALL
	CREATIVE_AD_TYPE_OFFERWALL
	CREATIVE_AD_TYPE_INTERSTITIAL_VIDEO
	CREATIVE_AD_TYPE_NATIVE_VIDEO
	CREATIVE_AD_TYPE_REWARDED_VIDEO
	CREATIVE_AD_TYPE_INSTREAM_VIDEO
)
