// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ksyun.proto

package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 视频版权信息
type CopyRight int32

const (
	CopyRight_CR_NONE  CopyRight = 0
	CopyRight_CR_EXIST CopyRight = 1
	CopyRight_CR_UGC   CopyRight = 2
	CopyRight_CR_OTHER CopyRight = 3
)

var CopyRight_name = map[int32]string{
	0: "CR_NONE",
	1: "CR_EXIST",
	2: "CR_UGC",
	3: "CR_OTHER",
}
var CopyRight_value = map[string]int32{
	"CR_NONE":  0,
	"CR_EXIST": 1,
	"CR_UGC":   2,
	"CR_OTHER": 3,
}

func (x CopyRight) String() string {
	return proto.EnumName(CopyRight_name, int32(x))
}
func (CopyRight) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{0}
}

// 设备类型
type DeviceType int32

const (
	DeviceType_DEVICETYPE_DEFAULT DeviceType = 0
	DeviceType_PHONE              DeviceType = 1
	DeviceType_TABLET             DeviceType = 2
	DeviceType_PC                 DeviceType = 3
)

var DeviceType_name = map[int32]string{
	0: "DEVICETYPE_DEFAULT",
	1: "PHONE",
	2: "TABLET",
	3: "PC",
}
var DeviceType_value = map[string]int32{
	"DEVICETYPE_DEFAULT": 0,
	"PHONE":              1,
	"TABLET":             2,
	"PC":                 3,
}

func (x DeviceType) String() string {
	return proto.EnumName(DeviceType_name, int32(x))
}
func (DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{1}
}

// 操作系统类型
type OsType int32

const (
	OsType_OSTYPE_DEFAULT OsType = 0
	OsType_ANDROID        OsType = 1
	OsType_IOS            OsType = 2
	OsType_WP             OsType = 3
	OsType_OTHERS         OsType = 4
)

var OsType_name = map[int32]string{
	0: "OSTYPE_DEFAULT",
	1: "ANDROID",
	2: "IOS",
	3: "WP",
	4: "OTHERS",
}
var OsType_value = map[string]int32{
	"OSTYPE_DEFAULT": 0,
	"ANDROID":        1,
	"IOS":            2,
	"WP":             3,
	"OTHERS":         4,
}

func (x OsType) String() string {
	return proto.EnumName(OsType_name, int32(x))
}
func (OsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{2}
}

// 当前设备屏幕状态
type ScreenType int32

const (
	ScreenType_SCREENTYPE_DEFAULT ScreenType = 0
	ScreenType_ERECT              ScreenType = 1
	ScreenType_ACROSS             ScreenType = 2
)

var ScreenType_name = map[int32]string{
	0: "SCREENTYPE_DEFAULT",
	1: "ERECT",
	2: "ACROSS",
}
var ScreenType_value = map[string]int32{
	"SCREENTYPE_DEFAULT": 0,
	"ERECT":              1,
	"ACROSS":             2,
}

func (x ScreenType) String() string {
	return proto.EnumName(ScreenType_name, int32(x))
}
func (ScreenType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{3}
}

// 广告位类型
type AdSlotType int32

const (
	AdSlotType_ENUM_ADSLOT_TYPE_DEFAULT          AdSlotType = 0
	AdSlotType_ENUM_ADSLOT_TYPE_BANNER           AdSlotType = 1
	AdSlotType_ENUM_ADSLOT_TYPE_INTERSTITIAL     AdSlotType = 2
	AdSlotType_ENUM_ADSLOT_TYPE_OPEN_SCREEN      AdSlotType = 4
	AdSlotType_ENUM_ADSLOT_TYPE_FEED             AdSlotType = 8
	AdSlotType_ENUM_ADSLOT_TYPE_REWARDED_VIDEO   AdSlotType = 9
	AdSlotType_ENUM_ADSLOT_TYPE_VIDEO_FRONT_FIT  AdSlotType = 21
	AdSlotType_ENUM_ADSLOT_TYPE_VIDEO_MIDDLE_FIT AdSlotType = 22
	AdSlotType_ENUM_ADSLOT_TYPE_VIDEO_END_FIT    AdSlotType = 23
	AdSlotType_ENUM_ADSLOT_TYPE_VIDEO_STOP       AdSlotType = 26
	AdSlotType_ENUM_ADSLOT_TYPE_COMMON_FLOAT     AdSlotType = 27
	AdSlotType_ENUM_ADSLOT_TYPE_VIDEO_EMBED      AdSlotType = 101
	AdSlotType_ENUM_ADSLOT_TYPE_VIDEO_SUSPEND    AdSlotType = 102
)

var AdSlotType_name = map[int32]string{
	0:   "ENUM_ADSLOT_TYPE_DEFAULT",
	1:   "ENUM_ADSLOT_TYPE_BANNER",
	2:   "ENUM_ADSLOT_TYPE_INTERSTITIAL",
	4:   "ENUM_ADSLOT_TYPE_OPEN_SCREEN",
	8:   "ENUM_ADSLOT_TYPE_FEED",
	9:   "ENUM_ADSLOT_TYPE_REWARDED_VIDEO",
	21:  "ENUM_ADSLOT_TYPE_VIDEO_FRONT_FIT",
	22:  "ENUM_ADSLOT_TYPE_VIDEO_MIDDLE_FIT",
	23:  "ENUM_ADSLOT_TYPE_VIDEO_END_FIT",
	26:  "ENUM_ADSLOT_TYPE_VIDEO_STOP",
	27:  "ENUM_ADSLOT_TYPE_COMMON_FLOAT",
	101: "ENUM_ADSLOT_TYPE_VIDEO_EMBED",
	102: "ENUM_ADSLOT_TYPE_VIDEO_SUSPEND",
}
var AdSlotType_value = map[string]int32{
	"ENUM_ADSLOT_TYPE_DEFAULT":          0,
	"ENUM_ADSLOT_TYPE_BANNER":           1,
	"ENUM_ADSLOT_TYPE_INTERSTITIAL":     2,
	"ENUM_ADSLOT_TYPE_OPEN_SCREEN":      4,
	"ENUM_ADSLOT_TYPE_FEED":             8,
	"ENUM_ADSLOT_TYPE_REWARDED_VIDEO":   9,
	"ENUM_ADSLOT_TYPE_VIDEO_FRONT_FIT":  21,
	"ENUM_ADSLOT_TYPE_VIDEO_MIDDLE_FIT": 22,
	"ENUM_ADSLOT_TYPE_VIDEO_END_FIT":    23,
	"ENUM_ADSLOT_TYPE_VIDEO_STOP":       26,
	"ENUM_ADSLOT_TYPE_COMMON_FLOAT":     27,
	"ENUM_ADSLOT_TYPE_VIDEO_EMBED":      101,
	"ENUM_ADSLOT_TYPE_VIDEO_SUSPEND":    102,
}

func (x AdSlotType) String() string {
	return proto.EnumName(AdSlotType_name, int32(x))
}
func (AdSlotType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{4}
}

// 物料轮替类型。web专有
type TurnType int32

const (
	TurnType_TURNTYPE_NONE TurnType = 0
	TurnType_WEIGHT        TurnType = 1
	TurnType_CAROUSEL      TurnType = 2
)

var TurnType_name = map[int32]string{
	0: "TURNTYPE_NONE",
	1: "WEIGHT",
	2: "CAROUSEL",
}
var TurnType_value = map[string]int32{
	"TURNTYPE_NONE": 0,
	"WEIGHT":        1,
	"CAROUSEL":      2,
}

func (x TurnType) String() string {
	return proto.EnumName(TurnType_name, int32(x))
}
func (TurnType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{5}
}

// 网络连接类型
type ConnectionType int32

const (
	ConnectionType_CONNECTION_UNKNOWN ConnectionType = 0
	ConnectionType_CELL_UNKNOWN       ConnectionType = 1
	ConnectionType_CELL_2G            ConnectionType = 2
	ConnectionType_CELL_3G            ConnectionType = 3
	ConnectionType_CELL_4G            ConnectionType = 4
	ConnectionType_CELL_5G            ConnectionType = 5
	ConnectionType_WIFI               ConnectionType = 100
	ConnectionType_ETHERNET           ConnectionType = 101
	ConnectionType_NEW_TYPE           ConnectionType = 999
)

var ConnectionType_name = map[int32]string{
	0:   "CONNECTION_UNKNOWN",
	1:   "CELL_UNKNOWN",
	2:   "CELL_2G",
	3:   "CELL_3G",
	4:   "CELL_4G",
	5:   "CELL_5G",
	100: "WIFI",
	101: "ETHERNET",
	999: "NEW_TYPE",
}
var ConnectionType_value = map[string]int32{
	"CONNECTION_UNKNOWN": 0,
	"CELL_UNKNOWN":       1,
	"CELL_2G":            2,
	"CELL_3G":            3,
	"CELL_4G":            4,
	"CELL_5G":            5,
	"WIFI":               100,
	"ETHERNET":           101,
	"NEW_TYPE":           999,
}

func (x ConnectionType) String() string {
	return proto.EnumName(ConnectionType_name, int32(x))
}
func (ConnectionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{6}
}

// 移动运营商类型
type OperatorType int32

const (
	OperatorType_UNKNOWN_OPERATOR OperatorType = 0
	OperatorType_CHINA_MOBILE     OperatorType = 1
	OperatorType_CHINA_TELECOM    OperatorType = 2
	OperatorType_CHINA_UNICOM     OperatorType = 3
	OperatorType_OTHER_OPERATOR   OperatorType = 99
)

var OperatorType_name = map[int32]string{
	0:  "UNKNOWN_OPERATOR",
	1:  "CHINA_MOBILE",
	2:  "CHINA_TELECOM",
	3:  "CHINA_UNICOM",
	99: "OTHER_OPERATOR",
}
var OperatorType_value = map[string]int32{
	"UNKNOWN_OPERATOR": 0,
	"CHINA_MOBILE":     1,
	"CHINA_TELECOM":    2,
	"CHINA_UNICOM":     3,
	"OTHER_OPERATOR":   99,
}

func (x OperatorType) String() string {
	return proto.EnumName(OperatorType_name, int32(x))
}
func (OperatorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{7}
}

// GPS坐标类型
type CoordinateType int32

const (
	CoordinateType_CT_NONE CoordinateType = 0
	CoordinateType_WGS84   CoordinateType = 1
	CoordinateType_GCJ02   CoordinateType = 2
	CoordinateType_BD09    CoordinateType = 3
)

var CoordinateType_name = map[int32]string{
	0: "CT_NONE",
	1: "WGS84",
	2: "GCJ02",
	3: "BD09",
}
var CoordinateType_value = map[string]int32{
	"CT_NONE": 0,
	"WGS84":   1,
	"GCJ02":   2,
	"BD09":    3,
}

func (x CoordinateType) String() string {
	return proto.EnumName(CoordinateType_name, int32(x))
}
func (CoordinateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{8}
}

// 性别枚举
type ESexType int32

const (
	ESexType_ESEX_UNKNOWN ESexType = 0
	ESexType_ESEX_MALE    ESexType = 1
	ESexType_ESEX_FEMALE  ESexType = 2
)

var ESexType_name = map[int32]string{
	0: "ESEX_UNKNOWN",
	1: "ESEX_MALE",
	2: "ESEX_FEMALE",
}
var ESexType_value = map[string]int32{
	"ESEX_UNKNOWN": 0,
	"ESEX_MALE":    1,
	"ESEX_FEMALE":  2,
}

func (x ESexType) String() string {
	return proto.EnumName(ESexType_name, int32(x))
}
func (ESexType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{9}
}

// 请求协议类型
type RequestProtocolType int32

const (
	RequestProtocolType_UNKNOWN_PROTOCOL_TYPE RequestProtocolType = 0
	RequestProtocolType_HTTP_PROTOCOL_TYPE    RequestProtocolType = 1
	RequestProtocolType_HTTPS_PROTOCOL_TYPE   RequestProtocolType = 2
)

var RequestProtocolType_name = map[int32]string{
	0: "UNKNOWN_PROTOCOL_TYPE",
	1: "HTTP_PROTOCOL_TYPE",
	2: "HTTPS_PROTOCOL_TYPE",
}
var RequestProtocolType_value = map[string]int32{
	"UNKNOWN_PROTOCOL_TYPE": 0,
	"HTTP_PROTOCOL_TYPE":    1,
	"HTTPS_PROTOCOL_TYPE":   2,
}

func (x RequestProtocolType) String() string {
	return proto.EnumName(RequestProtocolType_name, int32(x))
}
func (RequestProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{10}
}

// 创意类型
type CreativeType int32

const (
	CreativeType_NO_TYPE    CreativeType = 0
	CreativeType_TEXT       CreativeType = 1
	CreativeType_IMAGE      CreativeType = 2
	CreativeType_TEXT_ICON  CreativeType = 3
	CreativeType_VIDEO      CreativeType = 4
	CreativeType_VIDEO_HTML CreativeType = 9
	CreativeType_FEED_SMALL CreativeType = 81
	CreativeType_FEED_BIG   CreativeType = 82
	CreativeType_FEED_ARRA  CreativeType = 83
)

var CreativeType_name = map[int32]string{
	0:  "NO_TYPE",
	1:  "TEXT",
	2:  "IMAGE",
	3:  "TEXT_ICON",
	4:  "VIDEO",
	9:  "VIDEO_HTML",
	81: "FEED_SMALL",
	82: "FEED_BIG",
	83: "FEED_ARRA",
}
var CreativeType_value = map[string]int32{
	"NO_TYPE":    0,
	"TEXT":       1,
	"IMAGE":      2,
	"TEXT_ICON":  3,
	"VIDEO":      4,
	"VIDEO_HTML": 9,
	"FEED_SMALL": 81,
	"FEED_BIG":   82,
	"FEED_ARRA":  83,
}

func (x CreativeType) String() string {
	return proto.EnumName(CreativeType_name, int32(x))
}
func (CreativeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{11}
}

// 交互类型
type InteractionType int32

const (
	InteractionType_NO_INTERACTION InteractionType = 0
	InteractionType_SURFING        InteractionType = 1
	InteractionType_DOWNLOAD       InteractionType = 2
	InteractionType_OPTIONAL       InteractionType = 9
)

var InteractionType_name = map[int32]string{
	0: "NO_INTERACTION",
	1: "SURFING",
	2: "DOWNLOAD",
	9: "OPTIONAL",
}
var InteractionType_value = map[string]int32{
	"NO_INTERACTION": 0,
	"SURFING":        1,
	"DOWNLOAD":       2,
	"OPTIONAL":       9,
}

func (x InteractionType) String() string {
	return proto.EnumName(InteractionType_name, int32(x))
}
func (InteractionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{12}
}

// 广告展示过程事件类型
type TrackingEvent int32

const (
	// 广告展示过程共性事件
	TrackingEvent_AD_CLICK            TrackingEvent = 0
	TrackingEvent_AD_EXPOSURE         TrackingEvent = 1
	TrackingEvent_AD_CLOSE            TrackingEvent = 2
	TrackingEvent_AD_EXPOSURE_GENERAL TrackingEvent = 3
	TrackingEvent_AD_SKIP             TrackingEvent = 4
	// 视频类广告展示过程事件
	TrackingEvent_VIDEO_AD_START            TrackingEvent = 101000
	TrackingEvent_VIDEO_AD_FULL_SCREEN      TrackingEvent = 101001
	TrackingEvent_VIDEO_AD_END              TrackingEvent = 101002
	TrackingEvent_VIDEO_AD_START_CARD_CLICK TrackingEvent = 101003
	TrackingEvent_VIDEO_AD_CLOSE            TrackingEvent = 101009
	TrackingEvent_VIDEO_AD_RESTART          TrackingEvent = 101052
	TrackingEvent_VIDEO_AD_START_ACTIVE     TrackingEvent = 101004
	TrackingEvent_VIDEO_AD_PLAY_VALID       TrackingEvent = 101053
	// 下载类广告推广APP相关事件
	TrackingEvent_APP_AD_DOWNLOAD           TrackingEvent = 102000
	TrackingEvent_APP_AD_INSTALL            TrackingEvent = 102001
	TrackingEvent_APP_AD_ACTIVE             TrackingEvent = 102002
	TrackingEvent_APP_AD_START_DOWNLOAD     TrackingEvent = 102009
	TrackingEvent_APP_AD_START_INSTALL      TrackingEvent = 102010
	TrackingEvent_APP_AD_START_UNINSTALL    TrackingEvent = 102011
	TrackingEvent_APP_AD_START_MID_DOWNLOAD TrackingEvent = 102012
	// 去重点击类广告时事件
	TrackingEvent_APP_AD_UNIQUE_CLICK TrackingEvent = 103000
)

var TrackingEvent_name = map[int32]string{
	0:      "AD_CLICK",
	1:      "AD_EXPOSURE",
	2:      "AD_CLOSE",
	3:      "AD_EXPOSURE_GENERAL",
	4:      "AD_SKIP",
	101000: "VIDEO_AD_START",
	101001: "VIDEO_AD_FULL_SCREEN",
	101002: "VIDEO_AD_END",
	101003: "VIDEO_AD_START_CARD_CLICK",
	101009: "VIDEO_AD_CLOSE",
	101052: "VIDEO_AD_RESTART",
	101004: "VIDEO_AD_START_ACTIVE",
	101053: "VIDEO_AD_PLAY_VALID",
	102000: "APP_AD_DOWNLOAD",
	102001: "APP_AD_INSTALL",
	102002: "APP_AD_ACTIVE",
	102009: "APP_AD_START_DOWNLOAD",
	102010: "APP_AD_START_INSTALL",
	102011: "APP_AD_START_UNINSTALL",
	102012: "APP_AD_START_MID_DOWNLOAD",
	103000: "APP_AD_UNIQUE_CLICK",
}
var TrackingEvent_value = map[string]int32{
	"AD_CLICK":                  0,
	"AD_EXPOSURE":               1,
	"AD_CLOSE":                  2,
	"AD_EXPOSURE_GENERAL":       3,
	"AD_SKIP":                   4,
	"VIDEO_AD_START":            101000,
	"VIDEO_AD_FULL_SCREEN":      101001,
	"VIDEO_AD_END":              101002,
	"VIDEO_AD_START_CARD_CLICK": 101003,
	"VIDEO_AD_CLOSE":            101009,
	"VIDEO_AD_RESTART":          101052,
	"VIDEO_AD_START_ACTIVE":     101004,
	"VIDEO_AD_PLAY_VALID":       101053,
	"APP_AD_DOWNLOAD":           102000,
	"APP_AD_INSTALL":            102001,
	"APP_AD_ACTIVE":             102002,
	"APP_AD_START_DOWNLOAD":     102009,
	"APP_AD_START_INSTALL":      102010,
	"APP_AD_START_UNINSTALL":    102011,
	"APP_AD_START_MID_DOWNLOAD": 102012,
	"APP_AD_UNIQUE_CLICK":       103000,
}

func (x TrackingEvent) String() string {
	return proto.EnumName(TrackingEvent_name, int32(x))
}
func (TrackingEvent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{13}
}

// 版本号信息
type Version struct {
	Major                uint32   `protobuf:"varint,1,opt,name=major,proto3" json:"major,omitempty"`
	Minor                uint32   `protobuf:"varint,2,opt,name=minor,proto3" json:"minor,omitempty"`
	Micro                uint32   `protobuf:"varint,3,opt,name=micro,proto3" json:"micro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{0}
}
func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (dst *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(dst, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetMajor() uint32 {
	if m != nil {
		return m.Major
	}
	return 0
}

func (m *Version) GetMinor() uint32 {
	if m != nil {
		return m.Minor
	}
	return 0
}

func (m *Version) GetMicro() uint32 {
	if m != nil {
		return m.Micro
	}
	return 0
}

// 二维尺寸信息
type Size struct {
	Width                uint32   `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{1}
}
func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (dst *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(dst, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

func (m *Size) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Size) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

// 视频信息
type Video struct {
	Title                []byte    `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	ContentLength        uint32    `protobuf:"varint,2,opt,name=content_length,json=contentLength,proto3" json:"content_length,omitempty"`
	Copyright            CopyRight `protobuf:"varint,3,opt,name=copyright,proto3,enum=adx.CopyRight" json:"copyright,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{2}
}
func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (dst *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(dst, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Video) GetContentLength() uint32 {
	if m != nil {
		return m.ContentLength
	}
	return 0
}

func (m *Video) GetCopyright() CopyRight {
	if m != nil {
		return m.Copyright
	}
	return CopyRight_CR_NONE
}

// 唯一用户标识，优先使用明文，必需按要求填写，具体填写指导详见接口说明文档
type UdId struct {
	Idfa                 string   `protobuf:"bytes,1,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Imei                 string   `protobuf:"bytes,2,opt,name=imei,proto3" json:"imei,omitempty"`
	Mac                  string   `protobuf:"bytes,3,opt,name=mac,proto3" json:"mac,omitempty"`
	ImeiMd5              string   `protobuf:"bytes,4,opt,name=imei_md5,json=imeiMd5,proto3" json:"imei_md5,omitempty"`
	AndroidId            string   `protobuf:"bytes,5,opt,name=android_id,json=androidId,proto3" json:"android_id,omitempty"`
	IdfaMd5              string   `protobuf:"bytes,8,opt,name=idfa_md5,json=idfaMd5,proto3" json:"idfa_md5,omitempty"`
	AndroididMd5         string   `protobuf:"bytes,9,opt,name=androidid_md5,json=androididMd5,proto3" json:"androidid_md5,omitempty"`
	Ksid                 string   `protobuf:"bytes,15,opt,name=ksid,proto3" json:"ksid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UdId) Reset()         { *m = UdId{} }
func (m *UdId) String() string { return proto.CompactTextString(m) }
func (*UdId) ProtoMessage()    {}
func (*UdId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{3}
}
func (m *UdId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UdId.Unmarshal(m, b)
}
func (m *UdId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UdId.Marshal(b, m, deterministic)
}
func (dst *UdId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UdId.Merge(dst, src)
}
func (m *UdId) XXX_Size() int {
	return xxx_messageInfo_UdId.Size(m)
}
func (m *UdId) XXX_DiscardUnknown() {
	xxx_messageInfo_UdId.DiscardUnknown(m)
}

var xxx_messageInfo_UdId proto.InternalMessageInfo

func (m *UdId) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *UdId) GetImei() string {
	if m != nil {
		return m.Imei
	}
	return ""
}

func (m *UdId) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *UdId) GetImeiMd5() string {
	if m != nil {
		return m.ImeiMd5
	}
	return ""
}

func (m *UdId) GetAndroidId() string {
	if m != nil {
		return m.AndroidId
	}
	return ""
}

func (m *UdId) GetIdfaMd5() string {
	if m != nil {
		return m.IdfaMd5
	}
	return ""
}

func (m *UdId) GetAndroididMd5() string {
	if m != nil {
		return m.AndroididMd5
	}
	return ""
}

func (m *UdId) GetKsid() string {
	if m != nil {
		return m.Ksid
	}
	return ""
}

// 设备信息
type Device struct {
	DeviceType           DeviceType `protobuf:"varint,1,opt,name=device_type,json=deviceType,proto3,enum=adx.DeviceType" json:"device_type,omitempty"`
	OsType               OsType     `protobuf:"varint,2,opt,name=os_type,json=osType,proto3,enum=adx.OsType" json:"os_type,omitempty"`
	OsVersion            *Version   `protobuf:"bytes,3,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Vendor               []byte     `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model                []byte     `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	Udid                 *UdId      `protobuf:"bytes,6,opt,name=udid,proto3" json:"udid,omitempty"`
	ScreenSize           *Size      `protobuf:"bytes,7,opt,name=screen_size,json=screenSize,proto3" json:"screen_size,omitempty"`
	ScreenType           ScreenType `protobuf:"varint,8,opt,name=screen_type,json=screenType,proto3,enum=adx.ScreenType" json:"screen_type,omitempty"`
	Ua                   string     `protobuf:"bytes,14,opt,name=ua,proto3" json:"ua,omitempty"`
	Referer              string     `protobuf:"bytes,15,opt,name=referer,proto3" json:"referer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{4}
}
func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (dst *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(dst, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetDeviceType() DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return DeviceType_DEVICETYPE_DEFAULT
}

func (m *Device) GetOsType() OsType {
	if m != nil {
		return m.OsType
	}
	return OsType_OSTYPE_DEFAULT
}

func (m *Device) GetOsVersion() *Version {
	if m != nil {
		return m.OsVersion
	}
	return nil
}

func (m *Device) GetVendor() []byte {
	if m != nil {
		return m.Vendor
	}
	return nil
}

func (m *Device) GetModel() []byte {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *Device) GetUdid() *UdId {
	if m != nil {
		return m.Udid
	}
	return nil
}

func (m *Device) GetScreenSize() *Size {
	if m != nil {
		return m.ScreenSize
	}
	return nil
}

func (m *Device) GetScreenType() ScreenType {
	if m != nil {
		return m.ScreenType
	}
	return ScreenType_SCREENTYPE_DEFAULT
}

func (m *Device) GetUa() string {
	if m != nil {
		return m.Ua
	}
	return ""
}

func (m *Device) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

// 广告位请求信息
type AdSlot struct {
	AdslotId             string   `protobuf:"bytes,1,opt,name=adslot_id,json=adslotId,proto3" json:"adslot_id,omitempty"`
	AdslotSize           *Size    `protobuf:"bytes,2,opt,name=adslot_size,json=adslotSize,proto3" json:"adslot_size,omitempty"`
	Video                *Video   `protobuf:"bytes,4,opt,name=video,proto3" json:"video,omitempty"`
	AdslotType           uint32   `protobuf:"varint,5,opt,name=adslot_type,json=adslotType,proto3" json:"adslot_type,omitempty"`
	MinimumCpm           int32    `protobuf:"varint,6,opt,name=minimum_cpm,json=minimumCpm,proto3" json:"minimum_cpm,omitempty"`
	Ads                  uint32   `protobuf:"varint,15,opt,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdSlot) Reset()         { *m = AdSlot{} }
func (m *AdSlot) String() string { return proto.CompactTextString(m) }
func (*AdSlot) ProtoMessage()    {}
func (*AdSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{5}
}
func (m *AdSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdSlot.Unmarshal(m, b)
}
func (m *AdSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdSlot.Marshal(b, m, deterministic)
}
func (dst *AdSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdSlot.Merge(dst, src)
}
func (m *AdSlot) XXX_Size() int {
	return xxx_messageInfo_AdSlot.Size(m)
}
func (m *AdSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_AdSlot.DiscardUnknown(m)
}

var xxx_messageInfo_AdSlot proto.InternalMessageInfo

func (m *AdSlot) GetAdslotId() string {
	if m != nil {
		return m.AdslotId
	}
	return ""
}

func (m *AdSlot) GetAdslotSize() *Size {
	if m != nil {
		return m.AdslotSize
	}
	return nil
}

func (m *AdSlot) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *AdSlot) GetAdslotType() uint32 {
	if m != nil {
		return m.AdslotType
	}
	return 0
}

func (m *AdSlot) GetMinimumCpm() int32 {
	if m != nil {
		return m.MinimumCpm
	}
	return 0
}

func (m *AdSlot) GetAds() uint32 {
	if m != nil {
		return m.Ads
	}
	return 0
}

// 应用信息
type App struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	ChannelId            string   `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	AppVersion           *Version `protobuf:"bytes,3,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	AppPackage           string   `protobuf:"bytes,4,opt,name=app_package,json=appPackage,proto3" json:"app_package,omitempty"`
	SdkVersion           *Version `protobuf:"bytes,15,opt,name=sdk_version,json=sdkVersion,proto3" json:"sdk_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{6}
}
func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (dst *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(dst, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *App) GetChannelId() string {
	if m != nil {
		return m.ChannelId
	}
	return ""
}

func (m *App) GetAppVersion() *Version {
	if m != nil {
		return m.AppVersion
	}
	return nil
}

func (m *App) GetAppPackage() string {
	if m != nil {
		return m.AppPackage
	}
	return ""
}

func (m *App) GetSdkVersion() *Version {
	if m != nil {
		return m.SdkVersion
	}
	return nil
}

// WiFi热点信息
type WiFiAp struct {
	ApMac                string   `protobuf:"bytes,1,opt,name=ap_mac,json=apMac,proto3" json:"ap_mac,omitempty"`
	Rssi                 int32    `protobuf:"varint,2,opt,name=rssi,proto3" json:"rssi,omitempty"`
	ApName               []byte   `protobuf:"bytes,3,opt,name=ap_name,json=apName,proto3" json:"ap_name,omitempty"`
	IsConnected          bool     `protobuf:"varint,4,opt,name=is_connected,json=isConnected,proto3" json:"is_connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WiFiAp) Reset()         { *m = WiFiAp{} }
func (m *WiFiAp) String() string { return proto.CompactTextString(m) }
func (*WiFiAp) ProtoMessage()    {}
func (*WiFiAp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{7}
}
func (m *WiFiAp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiFiAp.Unmarshal(m, b)
}
func (m *WiFiAp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiFiAp.Marshal(b, m, deterministic)
}
func (dst *WiFiAp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiFiAp.Merge(dst, src)
}
func (m *WiFiAp) XXX_Size() int {
	return xxx_messageInfo_WiFiAp.Size(m)
}
func (m *WiFiAp) XXX_DiscardUnknown() {
	xxx_messageInfo_WiFiAp.DiscardUnknown(m)
}

var xxx_messageInfo_WiFiAp proto.InternalMessageInfo

func (m *WiFiAp) GetApMac() string {
	if m != nil {
		return m.ApMac
	}
	return ""
}

func (m *WiFiAp) GetRssi() int32 {
	if m != nil {
		return m.Rssi
	}
	return 0
}

func (m *WiFiAp) GetApName() []byte {
	if m != nil {
		return m.ApName
	}
	return nil
}

func (m *WiFiAp) GetIsConnected() bool {
	if m != nil {
		return m.IsConnected
	}
	return false
}

// 网络环境信息
type Network struct {
	Ipv4                 string         `protobuf:"bytes,1,opt,name=ipv4,proto3" json:"ipv4,omitempty"`
	ConnectionType       ConnectionType `protobuf:"varint,2,opt,name=connection_type,json=connectionType,proto3,enum=adx.ConnectionType" json:"connection_type,omitempty"`
	OperatorType         OperatorType   `protobuf:"varint,3,opt,name=operator_type,json=operatorType,proto3,enum=adx.OperatorType" json:"operator_type,omitempty"`
	CellularId           string         `protobuf:"bytes,4,opt,name=cellular_id,json=cellularId,proto3" json:"cellular_id,omitempty"`
	WifiAps              []*WiFiAp      `protobuf:"bytes,5,rep,name=wifi_aps,json=wifiAps,proto3" json:"wifi_aps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{8}
}
func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (dst *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(dst, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetIpv4() string {
	if m != nil {
		return m.Ipv4
	}
	return ""
}

func (m *Network) GetConnectionType() ConnectionType {
	if m != nil {
		return m.ConnectionType
	}
	return ConnectionType_CONNECTION_UNKNOWN
}

func (m *Network) GetOperatorType() OperatorType {
	if m != nil {
		return m.OperatorType
	}
	return OperatorType_UNKNOWN_OPERATOR
}

func (m *Network) GetCellularId() string {
	if m != nil {
		return m.CellularId
	}
	return ""
}

func (m *Network) GetWifiAps() []*WiFiAp {
	if m != nil {
		return m.WifiAps
	}
	return nil
}

// GPS信息
type Gps struct {
	CoordinateType       CoordinateType `protobuf:"varint,1,opt,name=coordinate_type,json=coordinateType,proto3,enum=adx.CoordinateType" json:"coordinate_type,omitempty"`
	Longitude            float64        `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float64        `protobuf:"fixed64,3,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Timestamp            uint32         `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Gps) Reset()         { *m = Gps{} }
func (m *Gps) String() string { return proto.CompactTextString(m) }
func (*Gps) ProtoMessage()    {}
func (*Gps) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{9}
}
func (m *Gps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gps.Unmarshal(m, b)
}
func (m *Gps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gps.Marshal(b, m, deterministic)
}
func (dst *Gps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gps.Merge(dst, src)
}
func (m *Gps) XXX_Size() int {
	return xxx_messageInfo_Gps.Size(m)
}
func (m *Gps) XXX_DiscardUnknown() {
	xxx_messageInfo_Gps.DiscardUnknown(m)
}

var xxx_messageInfo_Gps proto.InternalMessageInfo

func (m *Gps) GetCoordinateType() CoordinateType {
	if m != nil {
		return m.CoordinateType
	}
	return CoordinateType_CT_NONE
}

func (m *Gps) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Gps) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Gps) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// 用户信息
type STUserInfo struct {
	Gender               ESexType `protobuf:"varint,1,opt,name=gender,proto3,enum=adx.ESexType" json:"gender,omitempty"`
	Birthday             int32    `protobuf:"zigzag32,2,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Keywords             []string `protobuf:"bytes,3,rep,name=keywords,proto3" json:"keywords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STUserInfo) Reset()         { *m = STUserInfo{} }
func (m *STUserInfo) String() string { return proto.CompactTextString(m) }
func (*STUserInfo) ProtoMessage()    {}
func (*STUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{10}
}
func (m *STUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STUserInfo.Unmarshal(m, b)
}
func (m *STUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STUserInfo.Marshal(b, m, deterministic)
}
func (dst *STUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STUserInfo.Merge(dst, src)
}
func (m *STUserInfo) XXX_Size() int {
	return xxx_messageInfo_STUserInfo.Size(m)
}
func (m *STUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_STUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_STUserInfo proto.InternalMessageInfo

func (m *STUserInfo) GetGender() ESexType {
	if m != nil {
		return m.Gender
	}
	return ESexType_ESEX_UNKNOWN
}

func (m *STUserInfo) GetBirthday() int32 {
	if m != nil {
		return m.Birthday
	}
	return 0
}

func (m *STUserInfo) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

// 交易请求
type STExchangeReq struct {
	RequestId            string              `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ApiVersion           *Version            `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	Adslot               *AdSlot             `protobuf:"bytes,3,opt,name=adslot,proto3" json:"adslot,omitempty"`
	App                  *App                `protobuf:"bytes,4,opt,name=app,proto3" json:"app,omitempty"`
	Device               *Device             `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`
	Network              *Network            `protobuf:"bytes,6,opt,name=network,proto3" json:"network,omitempty"`
	Gps                  *Gps                `protobuf:"bytes,7,opt,name=gps,proto3" json:"gps,omitempty"`
	User                 *STUserInfo         `protobuf:"bytes,8,opt,name=user,proto3" json:"user,omitempty"`
	RequestProtocolType  RequestProtocolType `protobuf:"varint,13,opt,name=request_protocol_type,json=requestProtocolType,proto3,enum=adx.RequestProtocolType" json:"request_protocol_type,omitempty"`
	SearchKey            string              `protobuf:"bytes,100,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *STExchangeReq) Reset()         { *m = STExchangeReq{} }
func (m *STExchangeReq) String() string { return proto.CompactTextString(m) }
func (*STExchangeReq) ProtoMessage()    {}
func (*STExchangeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{11}
}
func (m *STExchangeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STExchangeReq.Unmarshal(m, b)
}
func (m *STExchangeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STExchangeReq.Marshal(b, m, deterministic)
}
func (dst *STExchangeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STExchangeReq.Merge(dst, src)
}
func (m *STExchangeReq) XXX_Size() int {
	return xxx_messageInfo_STExchangeReq.Size(m)
}
func (m *STExchangeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_STExchangeReq.DiscardUnknown(m)
}

var xxx_messageInfo_STExchangeReq proto.InternalMessageInfo

func (m *STExchangeReq) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *STExchangeReq) GetApiVersion() *Version {
	if m != nil {
		return m.ApiVersion
	}
	return nil
}

func (m *STExchangeReq) GetAdslot() *AdSlot {
	if m != nil {
		return m.Adslot
	}
	return nil
}

func (m *STExchangeReq) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *STExchangeReq) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *STExchangeReq) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *STExchangeReq) GetGps() *Gps {
	if m != nil {
		return m.Gps
	}
	return nil
}

func (m *STExchangeReq) GetUser() *STUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *STExchangeReq) GetRequestProtocolType() RequestProtocolType {
	if m != nil {
		return m.RequestProtocolType
	}
	return RequestProtocolType_UNKNOWN_PROTOCOL_TYPE
}

func (m *STExchangeReq) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

// 交易响应
type STExchangeRsp struct {
	RequestId            string   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrorCode            uint64   `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Ads                  []*Ad    `protobuf:"bytes,3,rep,name=ads,proto3" json:"ads,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *STExchangeRsp) Reset()         { *m = STExchangeRsp{} }
func (m *STExchangeRsp) String() string { return proto.CompactTextString(m) }
func (*STExchangeRsp) ProtoMessage()    {}
func (*STExchangeRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{12}
}
func (m *STExchangeRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_STExchangeRsp.Unmarshal(m, b)
}
func (m *STExchangeRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_STExchangeRsp.Marshal(b, m, deterministic)
}
func (dst *STExchangeRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_STExchangeRsp.Merge(dst, src)
}
func (m *STExchangeRsp) XXX_Size() int {
	return xxx_messageInfo_STExchangeRsp.Size(m)
}
func (m *STExchangeRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_STExchangeRsp.DiscardUnknown(m)
}

var xxx_messageInfo_STExchangeRsp proto.InternalMessageInfo

func (m *STExchangeRsp) GetRequestId() string {
	if m != nil {
		return m.RequestId
	}
	return ""
}

func (m *STExchangeRsp) GetErrorCode() uint64 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *STExchangeRsp) GetAds() []*Ad {
	if m != nil {
		return m.Ads
	}
	return nil
}

// 广告效果跟踪信息
type Tracking struct {
	TrackingEvent        TrackingEvent `protobuf:"varint,1,opt,name=tracking_event,json=trackingEvent,proto3,enum=adx.TrackingEvent" json:"tracking_event,omitempty"`
	TrackingUrl          []string      `protobuf:"bytes,2,rep,name=tracking_url,json=trackingUrl,proto3" json:"tracking_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Tracking) Reset()         { *m = Tracking{} }
func (m *Tracking) String() string { return proto.CompactTextString(m) }
func (*Tracking) ProtoMessage()    {}
func (*Tracking) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{13}
}
func (m *Tracking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracking.Unmarshal(m, b)
}
func (m *Tracking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracking.Marshal(b, m, deterministic)
}
func (dst *Tracking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracking.Merge(dst, src)
}
func (m *Tracking) XXX_Size() int {
	return xxx_messageInfo_Tracking.Size(m)
}
func (m *Tracking) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracking.DiscardUnknown(m)
}

var xxx_messageInfo_Tracking proto.InternalMessageInfo

func (m *Tracking) GetTrackingEvent() TrackingEvent {
	if m != nil {
		return m.TrackingEvent
	}
	return TrackingEvent_AD_CLICK
}

func (m *Tracking) GetTrackingUrl() []string {
	if m != nil {
		return m.TrackingUrl
	}
	return nil
}

// 广告元数据组索引结构
type MetaIndex struct {
	TotalNum             uint32   `protobuf:"varint,1,opt,name=total_num,json=totalNum,proto3" json:"total_num,omitempty"`
	CurrentIndex         uint32   `protobuf:"varint,2,opt,name=current_index,json=currentIndex,proto3" json:"current_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaIndex) Reset()         { *m = MetaIndex{} }
func (m *MetaIndex) String() string { return proto.CompactTextString(m) }
func (*MetaIndex) ProtoMessage()    {}
func (*MetaIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{14}
}
func (m *MetaIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaIndex.Unmarshal(m, b)
}
func (m *MetaIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaIndex.Marshal(b, m, deterministic)
}
func (dst *MetaIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaIndex.Merge(dst, src)
}
func (m *MetaIndex) XXX_Size() int {
	return xxx_messageInfo_MetaIndex.Size(m)
}
func (m *MetaIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaIndex.DiscardUnknown(m)
}

var xxx_messageInfo_MetaIndex proto.InternalMessageInfo

func (m *MetaIndex) GetTotalNum() uint32 {
	if m != nil {
		return m.TotalNum
	}
	return 0
}

func (m *MetaIndex) GetCurrentIndex() uint32 {
	if m != nil {
		return m.CurrentIndex
	}
	return 0
}

// 广告物料元数据信息
type MaterialMeta struct {
	CreativeType         CreativeType    `protobuf:"varint,1,opt,name=creative_type,json=creativeType,proto3,enum=adx.CreativeType" json:"creative_type,omitempty"`
	InteractionType      InteractionType `protobuf:"varint,2,opt,name=interaction_type,json=interactionType,proto3,enum=adx.InteractionType" json:"interaction_type,omitempty"`
	WinNoticeUrl         []string        `protobuf:"bytes,3,rep,name=win_notice_url,json=winNoticeUrl,proto3" json:"win_notice_url,omitempty"`
	ClickUrl             string          `protobuf:"bytes,4,opt,name=click_url,json=clickUrl,proto3" json:"click_url,omitempty"`
	Title                []byte          `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Description          [][]byte        `protobuf:"bytes,6,rep,name=description,proto3" json:"description,omitempty"`
	IconSrc              []string        `protobuf:"bytes,7,rep,name=iconSrc,proto3" json:"iconSrc,omitempty"`
	ImageSrc             []string        `protobuf:"bytes,8,rep,name=imageSrc,proto3" json:"imageSrc,omitempty"`
	AppPackage           string          `protobuf:"bytes,9,opt,name=app_package,json=appPackage,proto3" json:"app_package,omitempty"`
	AppSize              uint32          `protobuf:"varint,10,opt,name=app_size,json=appSize,proto3" json:"app_size,omitempty"`
	VideoUrl             string          `protobuf:"bytes,11,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"`
	VideoDuration        uint32          `protobuf:"varint,12,opt,name=video_duration,json=videoDuration,proto3" json:"video_duration,omitempty"`
	MetaIndex            *MetaIndex      `protobuf:"bytes,13,opt,name=meta_index,json=metaIndex,proto3" json:"meta_index,omitempty"`
	MaterialWidth        uint32          `protobuf:"varint,14,opt,name=material_width,json=materialWidth,proto3" json:"material_width,omitempty"`
	MaterialHeight       uint32          `protobuf:"varint,15,opt,name=material_height,json=materialHeight,proto3" json:"material_height,omitempty"`
	BrandName            string          `protobuf:"bytes,16,opt,name=brand_name,json=brandName,proto3" json:"brand_name,omitempty"`
	Ext                  string          `protobuf:"bytes,17,opt,name=ext,proto3" json:"ext,omitempty"`
	Source               string          `protobuf:"bytes,18,opt,name=source,proto3" json:"source,omitempty"`
	AppName              string          `protobuf:"bytes,19,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MaterialMeta) Reset()         { *m = MaterialMeta{} }
func (m *MaterialMeta) String() string { return proto.CompactTextString(m) }
func (*MaterialMeta) ProtoMessage()    {}
func (*MaterialMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{15}
}
func (m *MaterialMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaterialMeta.Unmarshal(m, b)
}
func (m *MaterialMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaterialMeta.Marshal(b, m, deterministic)
}
func (dst *MaterialMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterialMeta.Merge(dst, src)
}
func (m *MaterialMeta) XXX_Size() int {
	return xxx_messageInfo_MaterialMeta.Size(m)
}
func (m *MaterialMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterialMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MaterialMeta proto.InternalMessageInfo

func (m *MaterialMeta) GetCreativeType() CreativeType {
	if m != nil {
		return m.CreativeType
	}
	return CreativeType_NO_TYPE
}

func (m *MaterialMeta) GetInteractionType() InteractionType {
	if m != nil {
		return m.InteractionType
	}
	return InteractionType_NO_INTERACTION
}

func (m *MaterialMeta) GetWinNoticeUrl() []string {
	if m != nil {
		return m.WinNoticeUrl
	}
	return nil
}

func (m *MaterialMeta) GetClickUrl() string {
	if m != nil {
		return m.ClickUrl
	}
	return ""
}

func (m *MaterialMeta) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *MaterialMeta) GetDescription() [][]byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *MaterialMeta) GetIconSrc() []string {
	if m != nil {
		return m.IconSrc
	}
	return nil
}

func (m *MaterialMeta) GetImageSrc() []string {
	if m != nil {
		return m.ImageSrc
	}
	return nil
}

func (m *MaterialMeta) GetAppPackage() string {
	if m != nil {
		return m.AppPackage
	}
	return ""
}

func (m *MaterialMeta) GetAppSize() uint32 {
	if m != nil {
		return m.AppSize
	}
	return 0
}

func (m *MaterialMeta) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *MaterialMeta) GetVideoDuration() uint32 {
	if m != nil {
		return m.VideoDuration
	}
	return 0
}

func (m *MaterialMeta) GetMetaIndex() *MetaIndex {
	if m != nil {
		return m.MetaIndex
	}
	return nil
}

func (m *MaterialMeta) GetMaterialWidth() uint32 {
	if m != nil {
		return m.MaterialWidth
	}
	return 0
}

func (m *MaterialMeta) GetMaterialHeight() uint32 {
	if m != nil {
		return m.MaterialHeight
	}
	return 0
}

func (m *MaterialMeta) GetBrandName() string {
	if m != nil {
		return m.BrandName
	}
	return ""
}

func (m *MaterialMeta) GetExt() string {
	if m != nil {
		return m.Ext
	}
	return ""
}

func (m *MaterialMeta) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *MaterialMeta) GetAppName() string {
	if m != nil {
		return m.AppName
	}
	return ""
}

// 广告信息
type Ad struct {
	AdslotId             string          `protobuf:"bytes,1,opt,name=adslot_id,json=adslotId,proto3" json:"adslot_id,omitempty"`
	HtmlSnippet          []byte          `protobuf:"bytes,2,opt,name=html_snippet,json=htmlSnippet,proto3" json:"html_snippet,omitempty"`
	ExpirationTime       uint32          `protobuf:"varint,3,opt,name=expiration_time,json=expirationTime,proto3" json:"expiration_time,omitempty"`
	AdKey                string          `protobuf:"bytes,4,opt,name=ad_key,json=adKey,proto3" json:"ad_key,omitempty"`
	AdTracking           []*Tracking     `protobuf:"bytes,5,rep,name=ad_tracking,json=adTracking,proto3" json:"ad_tracking,omitempty"`
	MetaGroup            []*MaterialMeta `protobuf:"bytes,6,rep,name=meta_group,json=metaGroup,proto3" json:"meta_group,omitempty"`
	MobAdtext            string          `protobuf:"bytes,7,opt,name=mob_adtext,json=mobAdtext,proto3" json:"mob_adtext,omitempty"`
	MobAdlogo            string          `protobuf:"bytes,8,opt,name=mob_adlogo,json=mobAdlogo,proto3" json:"mob_adlogo,omitempty"`
	MaxCpm               int64           `protobuf:"varint,9,opt,name=max_cpm,json=maxCpm,proto3" json:"max_cpm,omitempty"`
	Vid                  string          `protobuf:"bytes,14,opt,name=vid,proto3" json:"vid,omitempty"`
	OpenMode             int32           `protobuf:"varint,15,opt,name=open_mode,json=openMode,proto3" json:"open_mode,omitempty"`
	SearchKey            string          `protobuf:"bytes,100,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}
func (*Ad) Descriptor() ([]byte, []int) {
	return fileDescriptor_ksyun_743b83578255dfa4, []int{16}
}
func (m *Ad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ad.Unmarshal(m, b)
}
func (m *Ad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ad.Marshal(b, m, deterministic)
}
func (dst *Ad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad.Merge(dst, src)
}
func (m *Ad) XXX_Size() int {
	return xxx_messageInfo_Ad.Size(m)
}
func (m *Ad) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad.DiscardUnknown(m)
}

var xxx_messageInfo_Ad proto.InternalMessageInfo

func (m *Ad) GetAdslotId() string {
	if m != nil {
		return m.AdslotId
	}
	return ""
}

func (m *Ad) GetHtmlSnippet() []byte {
	if m != nil {
		return m.HtmlSnippet
	}
	return nil
}

func (m *Ad) GetExpirationTime() uint32 {
	if m != nil {
		return m.ExpirationTime
	}
	return 0
}

func (m *Ad) GetAdKey() string {
	if m != nil {
		return m.AdKey
	}
	return ""
}

func (m *Ad) GetAdTracking() []*Tracking {
	if m != nil {
		return m.AdTracking
	}
	return nil
}

func (m *Ad) GetMetaGroup() []*MaterialMeta {
	if m != nil {
		return m.MetaGroup
	}
	return nil
}

func (m *Ad) GetMobAdtext() string {
	if m != nil {
		return m.MobAdtext
	}
	return ""
}

func (m *Ad) GetMobAdlogo() string {
	if m != nil {
		return m.MobAdlogo
	}
	return ""
}

func (m *Ad) GetMaxCpm() int64 {
	if m != nil {
		return m.MaxCpm
	}
	return 0
}

func (m *Ad) GetVid() string {
	if m != nil {
		return m.Vid
	}
	return ""
}

func (m *Ad) GetOpenMode() int32 {
	if m != nil {
		return m.OpenMode
	}
	return 0
}

func (m *Ad) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func init() {
	proto.RegisterType((*Version)(nil), "adx.Version")
	proto.RegisterType((*Size)(nil), "adx.Size")
	proto.RegisterType((*Video)(nil), "adx.Video")
	proto.RegisterType((*UdId)(nil), "adx.UdId")
	proto.RegisterType((*Device)(nil), "adx.Device")
	proto.RegisterType((*AdSlot)(nil), "adx.AdSlot")
	proto.RegisterType((*App)(nil), "adx.App")
	proto.RegisterType((*WiFiAp)(nil), "adx.WiFiAp")
	proto.RegisterType((*Network)(nil), "adx.Network")
	proto.RegisterType((*Gps)(nil), "adx.Gps")
	proto.RegisterType((*STUserInfo)(nil), "adx.STUserInfo")
	proto.RegisterType((*STExchangeReq)(nil), "adx.STExchangeReq")
	proto.RegisterType((*STExchangeRsp)(nil), "adx.STExchangeRsp")
	proto.RegisterType((*Tracking)(nil), "adx.Tracking")
	proto.RegisterType((*MetaIndex)(nil), "adx.MetaIndex")
	proto.RegisterType((*MaterialMeta)(nil), "adx.MaterialMeta")
	proto.RegisterType((*Ad)(nil), "adx.Ad")
	proto.RegisterEnum("adx.CopyRight", CopyRight_name, CopyRight_value)
	proto.RegisterEnum("adx.DeviceType", DeviceType_name, DeviceType_value)
	proto.RegisterEnum("adx.OsType", OsType_name, OsType_value)
	proto.RegisterEnum("adx.ScreenType", ScreenType_name, ScreenType_value)
	proto.RegisterEnum("adx.AdSlotType", AdSlotType_name, AdSlotType_value)
	proto.RegisterEnum("adx.TurnType", TurnType_name, TurnType_value)
	proto.RegisterEnum("adx.ConnectionType", ConnectionType_name, ConnectionType_value)
	proto.RegisterEnum("adx.OperatorType", OperatorType_name, OperatorType_value)
	proto.RegisterEnum("adx.CoordinateType", CoordinateType_name, CoordinateType_value)
	proto.RegisterEnum("adx.ESexType", ESexType_name, ESexType_value)
	proto.RegisterEnum("adx.RequestProtocolType", RequestProtocolType_name, RequestProtocolType_value)
	proto.RegisterEnum("adx.CreativeType", CreativeType_name, CreativeType_value)
	proto.RegisterEnum("adx.InteractionType", InteractionType_name, InteractionType_value)
	proto.RegisterEnum("adx.TrackingEvent", TrackingEvent_name, TrackingEvent_value)
}

func init() { proto.RegisterFile("ksyun.proto", fileDescriptor_ksyun_743b83578255dfa4) }

var fileDescriptor_ksyun_743b83578255dfa4 = []byte{
	// 2713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x57, 0xcb, 0x93, 0xdb, 0xc6,
	0xd1, 0x17, 0x1f, 0xcb, 0x47, 0xf3, 0xb1, 0xd0, 0xac, 0x1e, 0x94, 0x64, 0x7d, 0x5a, 0x51, 0x96,
	0x3f, 0x17, 0x13, 0xab, 0x54, 0xb2, 0x9c, 0xc4, 0x15, 0xa7, 0x12, 0x88, 0xc4, 0x52, 0x88, 0x48,
	0x80, 0x1e, 0x80, 0x5a, 0xf9, 0x84, 0x82, 0x80, 0xd1, 0x2e, 0xb2, 0x24, 0x00, 0x03, 0xe0, 0x6a,
	0xd7, 0xe7, 0x54, 0xe5, 0xe1, 0x5c, 0x72, 0xd8, 0x43, 0xca, 0x3a, 0xe6, 0xaf, 0x48, 0x25, 0x67,
	0xdf, 0x72, 0xce, 0x21, 0xa7, 0x5c, 0x72, 0x4d, 0x72, 0xcb, 0xe3, 0x90, 0x9a, 0x9e, 0x01, 0x96,
	0xab, 0x95, 0x95, 0x13, 0xa6, 0x7f, 0xdd, 0xd3, 0xd3, 0xdd, 0xd3, 0xdd, 0xd3, 0x80, 0xd6, 0x41,
	0x7a, 0xbc, 0x0a, 0xef, 0xc5, 0x49, 0x94, 0x45, 0xa4, 0xe2, 0xfa, 0x47, 0xfd, 0x27, 0x50, 0x7f,
	0xca, 0x92, 0x34, 0x88, 0x42, 0x72, 0x09, 0x36, 0x96, 0xee, 0x4f, 0xa2, 0xa4, 0x57, 0xda, 0x2e,
	0xbd, 0xdf, 0xa1, 0x82, 0x40, 0x34, 0x08, 0xa3, 0xa4, 0x57, 0x96, 0x28, 0x27, 0x04, 0xea, 0x25,
	0x51, 0xaf, 0x92, 0xa3, 0x5e, 0x12, 0xf5, 0x1f, 0x42, 0xd5, 0x0a, 0xbe, 0x60, 0x9c, 0xfb, 0x32,
	0xf0, 0xb3, 0xfd, 0x5c, 0x13, 0x12, 0xe4, 0x0a, 0xd4, 0xf6, 0x59, 0xb0, 0xb7, 0x9f, 0x49, 0x55,
	0x92, 0xea, 0x27, 0xb0, 0xf1, 0x34, 0xf0, 0x59, 0xc4, 0xb7, 0x65, 0x41, 0xb6, 0x60, 0xb8, 0xad,
	0x4d, 0x05, 0x41, 0xee, 0x42, 0xd7, 0x8b, 0xc2, 0x8c, 0x85, 0x99, 0xb3, 0x60, 0xe1, 0x5e, 0xb6,
	0x2f, 0xb7, 0x77, 0x24, 0x3a, 0x41, 0x90, 0x7c, 0x1b, 0x9a, 0x5e, 0x14, 0x1f, 0x27, 0x78, 0x00,
	0xb7, 0xaa, 0xfb, 0xa0, 0x7b, 0xcf, 0xf5, 0x8f, 0xee, 0x0d, 0xa3, 0xf8, 0x98, 0x72, 0x94, 0x9e,
	0x0a, 0xf4, 0xff, 0x58, 0x82, 0xea, 0xdc, 0xd7, 0x7d, 0x42, 0xa0, 0x1a, 0xf8, 0x2f, 0x5c, 0x3c,
	0xb2, 0x49, 0x71, 0x8d, 0xd8, 0x92, 0x05, 0x78, 0x0e, 0xc7, 0x96, 0x2c, 0x20, 0x0a, 0x54, 0x96,
	0xae, 0x87, 0x8a, 0x9b, 0x94, 0x2f, 0xc9, 0x35, 0x68, 0x70, 0x8e, 0xb3, 0xf4, 0x3f, 0xea, 0x55,
	0x11, 0xae, 0x73, 0x7a, 0xea, 0x7f, 0x44, 0x6e, 0x02, 0xb8, 0xa1, 0x9f, 0x44, 0x81, 0xef, 0x04,
	0x7e, 0x6f, 0x03, 0x99, 0x4d, 0x89, 0xe8, 0x3e, 0xee, 0xf4, 0x5f, 0xb8, 0xb8, 0xb3, 0x21, 0x77,
	0xfa, 0x2f, 0x5c, 0xbe, 0xf3, 0x0e, 0x74, 0xa4, 0x5c, 0xe0, 0x23, 0xbf, 0x89, 0xfc, 0x76, 0x01,
	0x72, 0x21, 0x02, 0xd5, 0x83, 0x34, 0xf0, 0x7b, 0x9b, 0xc2, 0x3e, 0xbe, 0xee, 0xff, 0xa5, 0x0c,
	0xb5, 0x11, 0x3b, 0x0c, 0x3c, 0x46, 0xee, 0x43, 0xcb, 0xc7, 0x95, 0x93, 0x1d, 0xc7, 0x22, 0x98,
	0xdd, 0x07, 0x9b, 0x18, 0x0b, 0x21, 0x61, 0x1f, 0xc7, 0x8c, 0x82, 0x5f, 0xac, 0xc9, 0xbb, 0x50,
	0x8f, 0x52, 0x21, 0x5d, 0x46, 0xe9, 0x16, 0x4a, 0x9b, 0x29, 0x4a, 0xd6, 0x22, 0xfc, 0x92, 0x6f,
	0x01, 0x44, 0xa9, 0x73, 0x28, 0xb2, 0x05, 0x23, 0xd1, 0x7a, 0xd0, 0x46, 0x41, 0x99, 0x41, 0xb4,
	0x19, 0xa5, 0x79, 0x32, 0x5d, 0x81, 0xda, 0x21, 0x0b, 0xfd, 0x28, 0xc1, 0xd8, 0xb4, 0xa9, 0xa4,
	0x30, 0x71, 0x22, 0x9f, 0x2d, 0x30, 0x2a, 0x6d, 0x2a, 0x08, 0x72, 0x13, 0xaa, 0x2b, 0x3f, 0xf0,
	0x7b, 0x35, 0x54, 0xda, 0x44, 0xa5, 0xfc, 0x7a, 0x28, 0xc2, 0x64, 0x00, 0xad, 0xd4, 0x4b, 0x18,
	0x0b, 0x9d, 0x34, 0xf8, 0x82, 0xf5, 0xea, 0x6b, 0x52, 0x3c, 0xdf, 0x28, 0x08, 0x2e, 0xe6, 0xde,
	0xfd, 0x42, 0x16, 0xfd, 0x69, 0xac, 0x79, 0x6f, 0x21, 0x2e, 0xbc, 0x4f, 0x8b, 0x35, 0xe9, 0x42,
	0x79, 0xe5, 0xf6, 0xba, 0x18, 0xcc, 0xf2, 0xca, 0x25, 0x3d, 0xa8, 0x27, 0xec, 0x05, 0x4b, 0x58,
	0x22, 0x23, 0x9c, 0x93, 0xfd, 0xaf, 0x4b, 0x50, 0x53, 0x7d, 0x6b, 0x11, 0x65, 0xe4, 0x06, 0x34,
	0x5d, 0x3f, 0x5d, 0x44, 0x19, 0xbf, 0x61, 0x91, 0x3c, 0x0d, 0x01, 0xe8, 0x68, 0xaf, 0x64, 0xa2,
	0xbd, 0xe5, 0x73, 0xf6, 0x0a, 0x2e, 0xda, 0xbb, 0x0d, 0x1b, 0x87, 0x3c, 0xfb, 0x31, 0x4e, 0xad,
	0x07, 0x20, 0x02, 0xca, 0x11, 0x2a, 0x18, 0xe4, 0x56, 0xa1, 0x0d, 0x3d, 0xda, 0xc0, 0xec, 0x97,
	0x2a, 0xd0, 0x81, 0x5b, 0xd0, 0x5a, 0x06, 0x61, 0xb0, 0x5c, 0x2d, 0x1d, 0x2f, 0x5e, 0x62, 0x10,
	0x37, 0x28, 0x48, 0x68, 0x18, 0x2f, 0x79, 0xf2, 0xba, 0x7e, 0x8a, 0xde, 0x74, 0x28, 0x5f, 0xf6,
	0x7f, 0x57, 0x82, 0x8a, 0x1a, 0xc7, 0xe4, 0x32, 0xd4, 0xdc, 0x38, 0x3e, 0xf5, 0x61, 0xc3, 0x8d,
	0x63, 0xdd, 0xe7, 0x09, 0xec, 0xed, 0xbb, 0x61, 0xc8, 0x16, 0x9c, 0x25, 0xea, 0xa0, 0x29, 0x11,
	0xdd, 0x27, 0x1f, 0x40, 0x8b, 0xef, 0x7a, 0x5b, 0x2a, 0x80, 0x1b, 0xc7, 0x79, 0x2e, 0xdc, 0x12,
	0xe2, 0xb1, 0xeb, 0x1d, 0xb8, 0x7b, 0x4c, 0x16, 0x0b, 0x17, 0x98, 0x09, 0x84, 0xeb, 0x4b, 0xfd,
	0x83, 0x42, 0xdf, 0xe6, 0x9b, 0xf4, 0xa5, 0xfe, 0x81, 0x5c, 0xf7, 0x23, 0xa8, 0xed, 0x06, 0x3b,
	0x81, 0x2a, 0xcd, 0x77, 0x78, 0x61, 0x16, 0xe6, 0x4f, 0x5d, 0x8f, 0x17, 0x48, 0x92, 0xa6, 0xa2,
	0x80, 0x37, 0x28, 0xae, 0xc9, 0x55, 0xa8, 0xbb, 0xb1, 0x13, 0xba, 0x4b, 0x86, 0xf6, 0xb6, 0x69,
	0xcd, 0x8d, 0x0d, 0x77, 0xc9, 0xc8, 0x6d, 0x68, 0x07, 0xa9, 0xe3, 0x45, 0x61, 0xc8, 0xbc, 0x8c,
	0xf9, 0x68, 0x5e, 0x83, 0xb6, 0x82, 0x74, 0x98, 0x43, 0xfd, 0x3f, 0x97, 0xa0, 0x6e, 0xb0, 0xec,
	0x65, 0x94, 0x1c, 0x60, 0x73, 0x88, 0x0f, 0x1f, 0x16, 0x0d, 0x23, 0x3e, 0x7c, 0x48, 0x3e, 0x81,
	0x4d, 0xb9, 0x3f, 0x88, 0xc2, 0xf5, 0x3a, 0xda, 0x92, 0x1d, 0x28, 0xe7, 0x61, 0xee, 0x75, 0xbd,
	0x33, 0x34, 0xf9, 0x0e, 0x74, 0xa2, 0x98, 0x25, 0x6e, 0x16, 0x25, 0x62, 0xaf, 0xe8, 0x5e, 0x17,
	0x45, 0x0d, 0x4a, 0x0e, 0xee, 0x6c, 0x47, 0x6b, 0x14, 0x0f, 0xab, 0xc7, 0x16, 0x8b, 0xd5, 0xc2,
	0x4d, 0xf8, 0x2d, 0xc9, 0xb0, 0xe6, 0x90, 0xee, 0x93, 0xf7, 0xa0, 0xf1, 0x32, 0x78, 0x11, 0x38,
	0x6e, 0x9c, 0xf6, 0x36, 0xb6, 0x2b, 0xef, 0xb7, 0x64, 0x5d, 0x8b, 0xe0, 0xd1, 0x3a, 0x67, 0xaa,
	0x71, 0xda, 0xff, 0xaa, 0x04, 0x95, 0x71, 0x9c, 0x0a, 0x37, 0xa2, 0xc4, 0x0f, 0x42, 0x37, 0x3b,
	0xd3, 0x3c, 0x72, 0x37, 0x72, 0x5e, 0xee, 0xc6, 0x3a, 0x4d, 0xde, 0x81, 0xe6, 0x22, 0x0a, 0xf7,
	0x82, 0x6c, 0xe5, 0x0b, 0xf7, 0x4b, 0xf4, 0x14, 0x20, 0xd7, 0xa1, 0xb1, 0x70, 0x33, 0xc1, 0xac,
	0x20, 0xb3, 0xa0, 0xf9, 0xce, 0x2c, 0x58, 0xb2, 0x34, 0x73, 0x97, 0x31, 0xba, 0xd1, 0xa1, 0xa7,
	0x40, 0xff, 0x00, 0xc0, 0xb2, 0xe7, 0x29, 0x4b, 0xf4, 0xf0, 0x45, 0x44, 0xee, 0x42, 0x6d, 0x8f,
	0x85, 0x3e, 0x4b, 0xa4, 0x69, 0x1d, 0x34, 0x4d, 0xb3, 0xd8, 0x91, 0xe8, 0x55, 0x82, 0xc9, 0x8f,
	0x7b, 0x1e, 0x24, 0xd9, 0xbe, 0xef, 0x1e, 0xa3, 0x2d, 0x17, 0x69, 0x41, 0x73, 0xde, 0x01, 0x3b,
	0x7e, 0x19, 0x25, 0x7e, 0xda, 0xab, 0x6c, 0x57, 0x78, 0xe5, 0xe6, 0x74, 0xff, 0x37, 0x15, 0xe8,
	0x58, 0xb6, 0x76, 0xc4, 0x73, 0x7d, 0x8f, 0x51, 0xf6, 0x39, 0x2f, 0x85, 0x84, 0x7d, 0xbe, 0x62,
	0xe9, 0x5a, 0xa5, 0x37, 0x25, 0x92, 0x97, 0x42, 0x50, 0xa4, 0x6e, 0xf9, 0xcd, 0xa5, 0x10, 0xe4,
	0xa5, 0x70, 0x07, 0x6a, 0xa2, 0x70, 0x65, 0xd1, 0x88, 0x0b, 0x11, 0x3d, 0x85, 0x4a, 0x16, 0xb9,
	0x0e, 0x15, 0x37, 0x8e, 0x65, 0x43, 0x68, 0x08, 0x89, 0x38, 0xa6, 0x1c, 0xe4, 0x0a, 0x44, 0xe3,
	0xc6, 0x3e, 0x90, 0x2b, 0x10, 0x7d, 0x9d, 0x4a, 0x16, 0x79, 0x0f, 0xea, 0xa1, 0x48, 0x57, 0xd9,
	0x51, 0x85, 0x41, 0x32, 0x85, 0x69, 0xce, 0xe4, 0x07, 0xed, 0xc5, 0xa9, 0xec, 0xa7, 0xe2, 0xa0,
	0x71, 0x9c, 0x52, 0x0e, 0x92, 0x3b, 0x50, 0x5d, 0xa5, 0x2c, 0xc1, 0x06, 0xda, 0xca, 0x1b, 0x68,
	0x71, 0x0f, 0x14, 0x99, 0x64, 0x02, 0x97, 0xf3, 0xe0, 0xe0, 0x4c, 0xe1, 0x45, 0x0b, 0x91, 0x37,
	0x1d, 0xbc, 0x9c, 0x1e, 0xee, 0xa2, 0x42, 0x62, 0x26, 0x05, 0xf0, 0x9e, 0xb6, 0x92, 0xf3, 0x20,
	0x0f, 0x75, 0xca, 0xdc, 0xc4, 0xdb, 0x77, 0x0e, 0xd8, 0x71, 0xcf, 0x17, 0xa1, 0x16, 0xc8, 0x13,
	0x76, 0xdc, 0xdf, 0x3f, 0x73, 0x35, 0x69, 0xfc, 0xbf, 0xae, 0xe6, 0x26, 0x00, 0x4b, 0x92, 0x28,
	0x71, 0xbc, 0x48, 0x66, 0x64, 0x95, 0x36, 0x11, 0x19, 0x46, 0x3e, 0x23, 0xd7, 0x44, 0x53, 0xac,
	0x60, 0x61, 0xd4, 0xe5, 0x3d, 0x88, 0xee, 0xb8, 0x0f, 0x0d, 0x3b, 0x71, 0xbd, 0x83, 0x20, 0xdc,
	0x23, 0x1f, 0x43, 0x37, 0x93, 0x6b, 0x87, 0x1d, 0xb2, 0x30, 0x93, 0x89, 0x47, 0x70, 0x47, 0x2e,
	0xa6, 0x71, 0x0e, 0xed, 0x64, 0xeb, 0x24, 0xef, 0x2c, 0xc5, 0xd6, 0x55, 0xb2, 0xe8, 0x95, 0x31,
	0xd9, 0x5a, 0x39, 0x36, 0x4f, 0x16, 0xfd, 0x29, 0x34, 0xa7, 0x2c, 0x73, 0xf5, 0xd0, 0x67, 0x47,
	0xfc, 0x4d, 0xc9, 0xa2, 0xcc, 0x5d, 0x38, 0xe1, 0x6a, 0x29, 0x47, 0xa7, 0x06, 0x02, 0xc6, 0x6a,
	0xc9, 0x27, 0x03, 0x6f, 0x95, 0x24, 0x7c, 0x0c, 0x0a, 0xb8, 0xb4, 0x9c, 0x82, 0xda, 0x12, 0x44,
	0x0d, 0xfd, 0xaf, 0x36, 0xa0, 0x3d, 0x75, 0x33, 0x96, 0x04, 0xee, 0x82, 0xeb, 0xe5, 0xbd, 0xc5,
	0x4b, 0x98, 0x9b, 0x05, 0x87, 0x67, 0x0a, 0x5a, 0xf4, 0x96, 0xa1, 0xe4, 0x88, 0xde, 0xe2, 0xad,
	0x51, 0xe4, 0x87, 0xa0, 0x04, 0x61, 0xc6, 0x12, 0xf7, 0x5c, 0x4b, 0xbb, 0x84, 0x5b, 0xf5, 0x53,
	0x26, 0xee, 0xde, 0x0c, 0xce, 0x02, 0xe4, 0x5d, 0xe8, 0xbe, 0x0c, 0x42, 0x27, 0x8c, 0x32, 0x3e,
	0x88, 0x70, 0xef, 0x45, 0xa9, 0xb5, 0x5f, 0x06, 0xa1, 0x81, 0xe0, 0x3c, 0x59, 0x70, 0x8f, 0xbd,
	0x45, 0xe0, 0x1d, 0xa0, 0x80, 0x68, 0x60, 0x0d, 0x04, 0x38, 0xb3, 0x18, 0x07, 0x37, 0xd6, 0xc7,
	0xc1, 0x6d, 0x3e, 0xdd, 0xa4, 0x5e, 0x12, 0xc4, 0xfc, 0xac, 0x5e, 0x6d, 0xbb, 0xf2, 0x7e, 0x9b,
	0xae, 0x43, 0xfc, 0xfd, 0x0e, 0xbc, 0x28, 0xb4, 0x12, 0xaf, 0x57, 0xc7, 0x33, 0x73, 0x92, 0x57,
	0x7e, 0xb0, 0x74, 0xf7, 0x18, 0x67, 0x35, 0x44, 0xe5, 0xe7, 0xf4, 0xeb, 0x8f, 0x54, 0xf3, 0xdc,
	0x23, 0x75, 0x0d, 0x1a, 0x5c, 0x00, 0x5f, 0x74, 0xc0, 0xd8, 0xd7, 0xdd, 0x38, 0xc6, 0x37, 0xfc,
	0x06, 0x34, 0xf1, 0xa9, 0x46, 0x37, 0x5a, 0xc2, 0x0d, 0x04, 0xb8, 0x1b, 0x77, 0xa1, 0x2b, 0x98,
	0xfe, 0x2a, 0x71, 0xd1, 0xe6, 0xb6, 0x98, 0x5f, 0x11, 0x1d, 0x49, 0x90, 0x7c, 0x00, 0xb0, 0x64,
	0x99, 0x2b, 0x2f, 0xb7, 0x83, 0x55, 0x27, 0x06, 0xd8, 0x22, 0x41, 0x68, 0x73, 0x59, 0xe4, 0xca,
	0x5d, 0xe8, 0x2e, 0xe5, 0x45, 0x3b, 0x62, 0xd6, 0xee, 0x0a, 0xad, 0x39, 0xba, 0x8b, 0x33, 0xf7,
	0xff, 0xc3, 0x66, 0x21, 0x26, 0x87, 0x6f, 0x31, 0x05, 0x14, 0xbb, 0x1f, 0x23, 0xca, 0x8b, 0xe5,
	0x79, 0xe2, 0x86, 0xbe, 0x78, 0x21, 0x15, 0x51, 0x4b, 0x88, 0xe0, 0x23, 0xa9, 0x40, 0x85, 0x1d,
	0x65, 0xbd, 0x8b, 0x62, 0xfc, 0x65, 0x47, 0x19, 0x1f, 0xf0, 0xd2, 0x68, 0x95, 0x78, 0xac, 0x47,
	0x10, 0x94, 0x54, 0x1e, 0x26, 0x54, 0xb3, 0x25, 0xc6, 0x27, 0x37, 0xc6, 0x97, 0xb6, 0xff, 0x65,
	0x05, 0xca, 0xaa, 0xff, 0xf6, 0xd1, 0xe9, 0x36, 0xb4, 0xf7, 0xb3, 0xe5, 0xc2, 0x49, 0xc3, 0x20,
	0x8e, 0x99, 0xf8, 0x55, 0x68, 0xd3, 0x16, 0xc7, 0x2c, 0x01, 0x71, 0x9f, 0xd8, 0x51, 0x1c, 0x88,
	0xb8, 0x39, 0xfc, 0xa1, 0x90, 0x7f, 0x21, 0xdd, 0x53, 0xd8, 0x0e, 0x96, 0x0c, 0xa7, 0x03, 0x1f,
	0x7b, 0x49, 0x55, 0x4e, 0x07, 0xfe, 0x13, 0x76, 0x4c, 0xee, 0xf1, 0x79, 0xca, 0xc9, 0xab, 0x50,
	0xbe, 0x8c, 0x9d, 0x33, 0xe5, 0xcc, 0xc7, 0xab, 0xa2, 0x03, 0xdc, 0x97, 0x37, 0xb3, 0x97, 0x44,
	0xab, 0x18, 0x13, 0xae, 0x25, 0x0b, 0x68, 0xbd, 0xd4, 0xc4, 0xe5, 0x8c, 0xb9, 0x0c, 0x0f, 0xe6,
	0x32, 0x7a, 0xee, 0xb8, 0x7e, 0xc6, 0x83, 0x56, 0x17, 0xc1, 0x5c, 0x46, 0xcf, 0x55, 0x04, 0x4e,
	0xd9, 0x8b, 0x68, 0x2f, 0x92, 0x7f, 0x00, 0x82, 0xcd, 0x01, 0x3e, 0xa9, 0x2c, 0xdd, 0x23, 0x1c,
	0xe5, 0x78, 0x16, 0x56, 0x68, 0x6d, 0xe9, 0x1e, 0xc9, 0x31, 0xee, 0x30, 0xf0, 0xe5, 0xa4, 0xca,
	0x97, 0x3c, 0x94, 0x51, 0xcc, 0x42, 0x87, 0x4f, 0xd1, 0x78, 0xb1, 0x1b, 0xb4, 0xc1, 0x81, 0x29,
	0x6f, 0x70, 0x6f, 0x6f, 0xa7, 0x83, 0x1f, 0x41, 0xb3, 0xf8, 0x35, 0x22, 0x2d, 0xa8, 0x0f, 0xa9,
	0x63, 0x98, 0x86, 0xa6, 0x5c, 0x20, 0x6d, 0x68, 0x0c, 0xa9, 0xa3, 0x3d, 0xd3, 0x2d, 0x5b, 0x29,
	0x11, 0x80, 0xda, 0x90, 0x3a, 0xf3, 0xf1, 0x50, 0x29, 0x4b, 0x8e, 0x69, 0x3f, 0xd6, 0xa8, 0x52,
	0x19, 0x0c, 0x01, 0x4e, 0x7f, 0x28, 0xc8, 0x15, 0x20, 0x23, 0xed, 0xa9, 0x3e, 0xd4, 0xec, 0xcf,
	0x66, 0x9a, 0x33, 0xd2, 0x76, 0xd4, 0xf9, 0xc4, 0x56, 0x2e, 0x90, 0x26, 0x6c, 0xcc, 0x1e, 0x73,
	0xc5, 0xa8, 0xca, 0x56, 0x1f, 0x4d, 0x34, 0x5b, 0x29, 0x93, 0x1a, 0x94, 0x67, 0x43, 0xa5, 0x32,
	0xd8, 0x81, 0x9a, 0xf8, 0xcf, 0x20, 0x04, 0xba, 0xa6, 0xf5, 0xda, 0xe6, 0x16, 0xd4, 0x55, 0x63,
	0x44, 0x4d, 0x7d, 0xa4, 0x94, 0x48, 0x1d, 0x2a, 0xba, 0x69, 0x89, 0xbd, 0xbb, 0x33, 0xa5, 0xc2,
	0xf5, 0xa1, 0x2d, 0x96, 0x52, 0x1d, 0x7c, 0x1f, 0xe0, 0x74, 0xbe, 0xe7, 0xc6, 0x58, 0x43, 0xaa,
	0x69, 0xc6, 0x79, 0x63, 0x34, 0xaa, 0x0d, 0xa5, 0x5f, 0xea, 0x90, 0x9a, 0x96, 0xa5, 0x94, 0x07,
	0x5f, 0x57, 0x00, 0xc4, 0x23, 0x2c, 0x47, 0x99, 0x9e, 0x66, 0xcc, 0xa7, 0x8e, 0x3a, 0xb2, 0x26,
	0xa6, 0xed, 0xbc, 0xa6, 0xe3, 0x06, 0x5c, 0x3d, 0xc7, 0x7d, 0xa4, 0x1a, 0x86, 0x46, 0x95, 0x12,
	0xb9, 0x0d, 0x37, 0xcf, 0x31, 0x75, 0xc3, 0xd6, 0xa8, 0x65, 0xeb, 0xb6, 0xae, 0x4e, 0x94, 0x32,
	0xd9, 0x86, 0x77, 0xce, 0x89, 0x98, 0x33, 0xcd, 0x70, 0x84, 0xc5, 0x4a, 0x95, 0x5c, 0x83, 0xcb,
	0xe7, 0x24, 0x76, 0x34, 0x6d, 0xa4, 0x34, 0xc8, 0x1d, 0xb8, 0x75, 0x8e, 0x45, 0xb5, 0x5d, 0x95,
	0x8e, 0xb4, 0x91, 0xf3, 0x54, 0x1f, 0x69, 0xa6, 0xd2, 0x24, 0xef, 0xc2, 0xf6, 0x39, 0x21, 0xe4,
	0x39, 0x3b, 0xd4, 0x34, 0x6c, 0x67, 0x47, 0xb7, 0x95, 0xcb, 0xe4, 0x2e, 0xdc, 0xfe, 0x06, 0xa9,
	0xa9, 0x3e, 0x1a, 0x4d, 0x34, 0x14, 0xbb, 0x42, 0xfa, 0xf0, 0x7f, 0xdf, 0x20, 0xa6, 0x19, 0x23,
	0x94, 0xb9, 0x4a, 0x6e, 0xc1, 0x8d, 0x6f, 0x90, 0xb1, 0x6c, 0x73, 0xa6, 0x5c, 0x7f, 0x63, 0x58,
	0x86, 0xe6, 0x74, 0x6a, 0x1a, 0xce, 0xce, 0xc4, 0x54, 0x6d, 0xe5, 0xc6, 0x1b, 0xc3, 0x22, 0xcf,
	0x99, 0x3e, 0xd2, 0x46, 0x0a, 0x7b, 0x8b, 0x25, 0xd6, 0xdc, 0x9a, 0x69, 0xc6, 0x48, 0x79, 0x31,
	0xf8, 0x2e, 0x34, 0xec, 0x55, 0x22, 0x92, 0xe0, 0x22, 0x74, 0xec, 0x39, 0x15, 0x29, 0x20, 0x53,
	0x1b, 0xa0, 0xb6, 0xab, 0xe9, 0xe3, 0xc7, 0x3c, 0x01, 0x78, 0x32, 0xab, 0xd4, 0x9c, 0x5b, 0xda,
	0x44, 0x29, 0x0f, 0x4e, 0x4a, 0xd0, 0x3d, 0x3b, 0xa8, 0xf3, 0x24, 0x1a, 0x9a, 0x86, 0xa1, 0x0d,
	0x6d, 0xdd, 0x34, 0x9c, 0xb9, 0xf1, 0xc4, 0x30, 0x77, 0x0d, 0xe5, 0x02, 0x51, 0xa0, 0x3d, 0xd4,
	0x26, 0x93, 0x02, 0x29, 0x61, 0xf9, 0x70, 0xe4, 0xc1, 0x58, 0x29, 0x17, 0xc4, 0x87, 0x63, 0xa5,
	0x52, 0x10, 0x0f, 0xc7, 0x4a, 0xb5, 0x20, 0x3e, 0x1a, 0x2b, 0x1b, 0xa4, 0x01, 0xd5, 0x5d, 0x7d,
	0x47, 0x57, 0x7c, 0x6e, 0x88, 0xc6, 0xd3, 0xd8, 0xd0, 0x6c, 0x85, 0x91, 0x0e, 0x34, 0x0c, 0x6d,
	0x17, 0xbd, 0x53, 0xfe, 0x5a, 0x1f, 0x44, 0xd0, 0x5e, 0xff, 0x07, 0x20, 0x97, 0x40, 0x91, 0xe7,
	0xf2, 0xa4, 0xa1, 0xaa, 0x6d, 0x52, 0x69, 0xd2, 0x63, 0xdd, 0x50, 0x9d, 0xa9, 0xf9, 0x48, 0x9f,
	0xf0, 0x5a, 0xbb, 0x08, 0x1d, 0x81, 0xd8, 0xda, 0x44, 0x1b, 0x9a, 0x53, 0xa5, 0x7c, 0x2a, 0x34,
	0x37, 0x74, 0x8e, 0x54, 0xb0, 0xe4, 0xf8, 0xc9, 0xa7, 0xaa, 0xbc, 0xc1, 0x0f, 0x78, 0x1c, 0xce,
	0x4c, 0xf6, 0xdc, 0x6c, 0x3b, 0x8f, 0x60, 0x13, 0x36, 0x76, 0xc7, 0xd6, 0xf7, 0x1e, 0x2a, 0x25,
	0xbe, 0x1c, 0x0f, 0x7f, 0x7c, 0xff, 0x81, 0x52, 0xe6, 0xce, 0x3c, 0x1a, 0xdd, 0xff, 0x58, 0xa9,
	0x0c, 0x3e, 0x81, 0x46, 0x3e, 0x8d, 0xf3, 0x03, 0x35, 0x4b, 0x7b, 0xb6, 0x16, 0xba, 0x0e, 0x34,
	0x11, 0x99, 0xaa, 0x68, 0xe4, 0x26, 0xb4, 0x90, 0xdc, 0xd1, 0x10, 0x28, 0x0f, 0x5c, 0xd8, 0x7a,
	0xc3, 0xb8, 0xc8, 0x0b, 0x22, 0x77, 0x7a, 0x46, 0x4d, 0xdb, 0x1c, 0x9a, 0x13, 0x11, 0xa0, 0x0b,
	0xfc, 0x92, 0x1e, 0xdb, 0xf6, 0xec, 0x35, 0xbc, 0x44, 0xae, 0xc2, 0x16, 0xc7, 0xad, 0xd7, 0x18,
	0xe5, 0xc1, 0xcf, 0x4a, 0xd0, 0x5e, 0x9f, 0x7c, 0xb8, 0x7b, 0x86, 0x99, 0xab, 0x6b, 0x40, 0xd5,
	0xd6, 0x9e, 0xd9, 0xc2, 0x3b, 0x7d, 0xaa, 0x8e, 0x35, 0xa5, 0xcc, 0xad, 0xe6, 0xa0, 0xa3, 0x0f,
	0x4d, 0x43, 0xa9, 0x70, 0x8e, 0xa8, 0xb4, 0x2a, 0xe9, 0x02, 0x88, 0x0c, 0x7c, 0x6c, 0x4f, 0x27,
	0x4a, 0x93, 0xd3, 0xbc, 0x50, 0x1d, 0x6b, 0xaa, 0x4e, 0x26, 0xca, 0xa7, 0xfc, 0x6a, 0x91, 0x7e,
	0xa4, 0x8f, 0x15, 0xca, 0xf5, 0x20, 0xa5, 0x52, 0xaa, 0x2a, 0xd6, 0xc0, 0x80, 0xcd, 0xd7, 0xe6,
	0x28, 0x7e, 0x21, 0x86, 0x29, 0x1a, 0x86, 0x8a, 0x69, 0x27, 0x7a, 0xa0, 0x35, 0xa7, 0x3b, 0xba,
	0x31, 0x16, 0x49, 0x3b, 0x32, 0x77, 0x8d, 0x89, 0xa9, 0x8e, 0x44, 0x3f, 0x36, 0x67, 0x5c, 0x4c,
	0x9d, 0x28, 0xcd, 0xc1, 0x4f, 0xab, 0xd0, 0x39, 0x33, 0x90, 0x72, 0xbe, 0x3a, 0x72, 0x86, 0x13,
	0x7d, 0xf8, 0x44, 0xb9, 0xc0, 0xa3, 0xad, 0x8e, 0x1c, 0xed, 0xd9, 0xcc, 0xb4, 0xe6, 0x54, 0x13,
	0xca, 0x90, 0x6d, 0x5a, 0xdc, 0xcb, 0xab, 0xb0, 0xb5, 0xc6, 0x76, 0xc6, 0x9a, 0xa1, 0x51, 0x75,
	0x22, 0x72, 0x58, 0x1d, 0x39, 0xd6, 0x13, 0x7d, 0xa6, 0x54, 0xc9, 0x25, 0xe8, 0x0a, 0x8f, 0x39,
	0x64, 0xab, 0xd4, 0x56, 0x7e, 0x7e, 0x52, 0x23, 0xd7, 0xe1, 0x52, 0x81, 0xee, 0xcc, 0x27, 0x93,
	0xbc, 0x97, 0xfd, 0xe2, 0xa4, 0x46, 0x08, 0xb4, 0x0b, 0x1e, 0x2f, 0xd2, 0x5f, 0x9e, 0xd4, 0xc8,
	0x2d, 0xb8, 0x76, 0x56, 0x8b, 0x33, 0x54, 0x69, 0x6e, 0xe9, 0x97, 0x27, 0xb5, 0x33, 0xc7, 0x08,
	0x03, 0x7f, 0x7d, 0x52, 0x23, 0x57, 0x40, 0x29, 0x50, 0xaa, 0x89, 0xe3, 0x7f, 0x7f, 0x52, 0x23,
	0x37, 0xe0, 0xf2, 0x6b, 0xea, 0x78, 0xf4, 0x9e, 0x6a, 0xca, 0xaf, 0x4e, 0x6a, 0xe4, 0x1a, 0x6c,
	0x15, 0xcc, 0xd9, 0x44, 0xfd, 0xcc, 0x79, 0xaa, 0x4e, 0xf4, 0x91, 0xf2, 0x87, 0x93, 0x1a, 0xb9,
	0x0c, 0x9b, 0xea, 0x6c, 0xc6, 0x19, 0x45, 0x50, 0xff, 0xf6, 0x0a, 0x0f, 0x97, 0xb0, 0x6e, 0x58,
	0x36, 0xbf, 0xc9, 0xbf, 0xbf, 0xaa, 0x91, 0x2d, 0xe8, 0x48, 0x54, 0x2a, 0xff, 0xc7, 0x2b, 0x3c,
	0x59, 0x82, 0xe2, 0xdc, 0x42, 0xcf, 0x3f, 0x5f, 0x61, 0x54, 0xce, 0x30, 0x73, 0x6d, 0xff, 0x7a,
	0x55, 0x23, 0xef, 0xc0, 0x95, 0x33, 0xbc, 0xb9, 0x91, 0x73, 0xff, 0xfd, 0x0a, 0xe3, 0x73, 0x86,
	0x3b, 0xd5, 0xd7, 0x4c, 0xfc, 0xcf, 0x2b, 0x74, 0x4a, 0x0a, 0xcc, 0x0d, 0xfd, 0xd3, 0xb9, 0x26,
	0x43, 0xf7, 0xa7, 0xdf, 0xd6, 0x9e, 0xd7, 0xf0, 0x57, 0xec, 0xc3, 0xff, 0x06, 0x00, 0x00, 0xff,
	0xff, 0xed, 0x07, 0x0f, 0xc7, 0xed, 0x15, 0x00, 0x00,
}
