// Code generated by protoc-gen-go. DO NOT EDIT.
// source: offer_material.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OfferMaterial struct {
	AdvCreativeId        string   `protobuf:"bytes,1,opt,name=advCreativeId,proto3" json:"advCreativeId,omitempty"`
	AdvCname             string   `protobuf:"bytes,2,opt,name=advCname,proto3" json:"advCname,omitempty"`
	Source               int32    `protobuf:"varint,3,opt,name=source,proto3" json:"source,omitempty"`
	OmID                 int64    `protobuf:"varint,4,opt,name=omID,proto3" json:"omID,omitempty"`
	CsetId               int64    `protobuf:"varint,5,opt,name=csetId,proto3" json:"csetId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OfferMaterial) Reset()         { *m = OfferMaterial{} }
func (m *OfferMaterial) String() string { return proto.CompactTextString(m) }
func (*OfferMaterial) ProtoMessage()    {}
func (*OfferMaterial) Descriptor() ([]byte, []int) {
	return fileDescriptor_33028c2f5c137cbc, []int{0}
}

func (m *OfferMaterial) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OfferMaterial.Unmarshal(m, b)
}
func (m *OfferMaterial) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OfferMaterial.Marshal(b, m, deterministic)
}
func (m *OfferMaterial) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OfferMaterial.Merge(m, src)
}
func (m *OfferMaterial) XXX_Size() int {
	return xxx_messageInfo_OfferMaterial.Size(m)
}
func (m *OfferMaterial) XXX_DiscardUnknown() {
	xxx_messageInfo_OfferMaterial.DiscardUnknown(m)
}

var xxx_messageInfo_OfferMaterial proto.InternalMessageInfo

func (m *OfferMaterial) GetAdvCreativeId() string {
	if m != nil {
		return m.AdvCreativeId
	}
	return ""
}

func (m *OfferMaterial) GetAdvCname() string {
	if m != nil {
		return m.AdvCname
	}
	return ""
}

func (m *OfferMaterial) GetSource() int32 {
	if m != nil {
		return m.Source
	}
	return 0
}

func (m *OfferMaterial) GetOmID() int64 {
	if m != nil {
		return m.OmID
	}
	return 0
}

func (m *OfferMaterial) GetCsetId() int64 {
	if m != nil {
		return m.CsetId
	}
	return 0
}

func init() {
	proto.RegisterType((*OfferMaterial)(nil), "protobuf.OfferMaterial")
}

func init() { proto.RegisterFile("offer_material.proto", fileDescriptor_33028c2f5c137cbc) }

var fileDescriptor_33028c2f5c137cbc = []byte{
	// 160 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xc9, 0x4f, 0x4b, 0x4b,
	0x2d, 0x8a, 0xcf, 0x4d, 0x2c, 0x49, 0x2d, 0xca, 0x4c, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x53, 0x19, 0xb9, 0x78, 0xfd, 0x41, 0x4a, 0x7c,
	0xa1, 0x2a, 0x84, 0x54, 0xb8, 0x78, 0x13, 0x53, 0xca, 0x9c, 0x8b, 0x52, 0x13, 0x4b, 0x32, 0xcb,
	0x52, 0x3d, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x50, 0x05, 0x85, 0xa4, 0xb8, 0x38,
	0x40, 0x02, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x4c, 0x60, 0x05, 0x70, 0xbe, 0x90, 0x18, 0x17, 0x5b,
	0x71, 0x7e, 0x69, 0x51, 0x72, 0xaa, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x94, 0x27, 0x24,
	0xc4, 0xc5, 0x92, 0x9f, 0xeb, 0xe9, 0x22, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0x66, 0x83,
	0xd4, 0x26, 0x17, 0xa7, 0x96, 0x78, 0xa6, 0x48, 0xb0, 0x82, 0x45, 0xa1, 0xbc, 0x24, 0x36, 0xb0,
	0x0b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3f, 0xda, 0x77, 0x1d, 0xc0, 0x00, 0x00, 0x00,
}
