package mvconst

const (
	REQUEST_TYPE_SDK = iota + 1
	REQUEST_TYPE_SITE
	REQUEST_TYPE_OPENAPI
	REQUEST_TYPE_SDK_OLD
	REQUEST_TYPE_AGENTAPI
	REQUEST_TYPE_SITE_OLD
	REQUEST_TYPE_OPENAPI_V3
	REQUEST_TYPE_DSP
	REQUEST_TYPE_OPENAPI_V4
	REQUEST_TYPE_OPENAPI_AD
)
