# encoding: console
info_filename: "/data/adn_logs/aladdin/monitor/monitor.log"
# error_filename: "/data/adn_logs/aladdin/monitor/monitor.log"
max_size: 10
max_backups: 3
max_age: 1
compress: true
division: "time"
level_separate: false
time_unit: "hour"
stacktrace: false
sample_rate: 0.0001   # 1w次错误记录一次