caches:
  - "redis"
# compressor:
#   package: "mykv"
#   class: "Compressor"
# serializer:
#   package: "mykv"
#   class: "Serializer"
gcache:
  class: "NoCache"
redis:
  class: "RedisClusterString"
  address: "adn-ip-cache-sg.rayjump.com:6379"
  poolSize: 30
  timeout: "100ms"
  retries: 0
  keyIdx: 8
  keyLen: 7