caches:
  - "aerospike"
# compressor:
#   package: "mykv"
#   class: "Compressor"
# serializer:
#   package: "mykv"
#   class: "Serializer"
gcache:
  class: "NoCache"
aerospike:
  class: "Aerospike"
  address: "adn-hb-aerospike-internal-vg-aws-1a.rayjump.com:3000"
  namespace: "adnet"
  setname: "aladdin"
  timeout: "600ms"
  writeTimeout: "500ms"
  expiration: "1h"
  retries: 1
  connectionQueueSize: 100