# encoding: console
info_filename: "/data/adn_logs/aladdin/load/load.log"
# error_filename: "/data/adn_logs/aladdin/load/load.log"
max_size: 10
max_backups: 3
max_age: 1
compress: true
division: "time"
level_separate: false
time_unit: "hour"
stacktrace: false