bid_log: "bid_log.yaml"
req_log: "req_log.yaml"
loss_req_log: "loss_req_log.yaml"
load_log: "load_log.yaml"
event_log: "event_log.yaml"
watch_log: "watch_log.yaml"
creative_log: "creative_log.yaml"
dsp_creative_log: "dsp_creative_log.yaml"
runtime_log: "runtime_log.yaml"
req_monitor_log: "req_monitor_log.yaml"
treasure_box_log: "treasure_box_log.yaml"
consul_aerospike_log: "consul_aerospike_log.yaml"
consul_adx_log: "consul_adx_log.yaml"
consul_watch_log: "consul_watch_log.yaml"
consul_adnet_aerospike_log: "consul_adnet_aerospike_log.yaml"
mapping_server_log: "mapping_server_log.yaml"
consul_mapping_server_log: "consul_mapping_server_log.yaml"
device_aerospike_log: "device_aerospike_log.yaml"
